// Generated by the Spar front-end

program



declarations [
    record __gc_reflink [next:pointer record __gc_reflink,nelm:int,elm:array pointer pointer record Object0,serial:int,magic:int],
    globalvariable __gc_globallink record __gc_reflink,
    globalvariable __gc_reflink_chain pointer record __gc_reflink,
    formalvariable __main_x __main_catchblock pointer record []
    ,
    localvariable a_0 scope0 pointer shape [dontcare] int cast pointer shape [dontcare] int null
    ,
    localvariable arr0_1 scope0 pointer shape [dontcare] int cast pointer shape [dontcare] int null
    ,
    localvariable v_0 scope1 int
    ,
    formalvariable a_1 scope2 pointer shape [dontcare] int final 
    ,
    function t_fn_0 [a_1] int pragma [noescapes=(@a_1)]
    statements scope2 [
        return ( (*notnullassert a_1, [0]), +, (*notnullassert a_1, [1]) )
    ]

    ,
    procedure t_main_0 []
    statements scope0 [
        assign field link0 next __gc_reflink_chain,
        assign field link0 nelm 2,
        assign field link0 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &a_0, cast pointer pointer record Object0 &arr0_1],
        assign field link0 serial 10000,
        assign field link0 magic 1917976149
        ,
        assign __gc_reflink_chain &link0
        ,
        assign arr0_1 nullednew shape [3] int null
        ,
        assign (*arr0_1, [0]) 1
        ,
        assign (*arr0_1, [1]) 2
        ,
        assign (*arr0_1, [2]) 3
        ,
        assign a_0 arr0_1
        ,
        statements scope1 [
            assign v_0 functioncall t_fn_0 [a_0]
        ]
    ]

    ,
    formalvariable x_0 scope3 pointer record Exception0 final 
    ,
    localvariable id_1 scope3 int
    ,
    formalvariable obj_0 Java_spar_compiler_Introspection_getClassId pointer record Object0 final 
    ,
    externalfunction Java_spar_compiler_Introspection_getClassId [obj_0] int pragma [noGC]
    ,
    localvariable s_0 scope4 string
    ,
    formalvariable id_2 Java_spar_compiler_Introspection_getClassName int final 
    ,
    externalfunction Java_spar_compiler_Introspection_getClassName [id_2] string pragma [noGC]
    ,
    formalvariable s_1 Java_spar_compiler_DefaultExceptionHandler_exit string final 
    ,
    externalprocedure Java_spar_compiler_DefaultExceptionHandler_exit [s_1] final  pragma [noGC]
    ,
    procedure spar_compiler_DefaultExceptionHandler_handler_0 [x_0] pragma [noGC]
    statements scope3 [
        assign id_1 functioncall Java_spar_compiler_Introspection_getClassId [cast pointer record Object0 x_0]
        ,
        statements scope4 [
            assign s_0 functioncall Java_spar_compiler_Introspection_getClassName [id_1]
            ,
            procedurecall Java_spar_compiler_DefaultExceptionHandler_exit [s_0]
        ]
    ]

    ,
    procedure spar_compiler_Builder_boundExit_1 [] pragma [noGC]
    statements [
        procedurecall Java_spar_compiler_DefaultExceptionHandler_exit ["Array bound violated"]
    ]

    ,
    localvariable breakout1_0 scope5 pointer record OutOfMemoryError0 cast pointer record OutOfMemoryError0 null
    ,
    formalvariable this_0 scope6 pointer record OutOfMemoryError0 final 
    ,
    formalvariable this_1 scope7 pointer record VirtualMachineError0 final 
    ,
    formalvariable this_2 scope8 pointer record Error0 final 
    ,
    formalvariable this_3 scope9 pointer record Throwable0 final 
    ,
    formalvariable this_4 scopea pointer record Object0 final 
    ,
    procedure java_lang_Object_Object_0 [this_4] pragma [noescapes=(@this_4)]
    statements scopea [
    ]

    ,
    formalvariable this_5 scopeb pointer record Throwable0 final 
    ,
    procedure java_lang_Throwable_dynamic_init_Throwable0_0 [this_5] pragma [noescapes=(@this_5)]
    statements scopeb [
        assign field *this_5 java_lang_Throwable_backtrace_0 cast pointer record Object0 null
        ,
        assign field *this_5 java_lang_Throwable_message_0 cast pointer record String0 null
    ]

    ,
    localvariable x_1 scopec pointer record Throwable0 cast pointer record Throwable0 null
    ,
    formalvariable this_6 Java_java_lang_Throwable_fillInStackTrace pointer record Throwable0 final 
    ,
    externalfunction Java_java_lang_Throwable_fillInStackTrace [this_6] pointer record Throwable0
    ,
    procedure java_lang_Throwable_Throwable_0 [this_3]
    statements scope9 [
        assign field link1 next __gc_reflink_chain,
        assign field link1 nelm 1,
        assign field link1 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &this_3],
        assign field link1 serial 10001,
        assign field link1 magic 1917976149
        ,
        assign __gc_reflink_chain &link1
        ,
        procedurecall java_lang_Object_Object_0 [cast pointer record Object0 this_3]
        ,
        assign __gc_reflink_chain &link1
        ,
        procedurecall java_lang_Throwable_dynamic_init_Throwable0_0 [this_3]
        ,
        assign field *this_3 java_lang_Throwable_message_0 cast pointer record String0 null
        ,
        assign __gc_reflink_chain &link1
        ,
        statements scopec [
            assign field link2 next &link1,
            assign field link2 nelm 1,
            assign field link2 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &x_1],
            assign field link2 serial 10002,
            assign field link2 magic 1917976149
            ,
            assign __gc_reflink_chain &link2
            ,
            assign x_1 functioncall Java_java_lang_Throwable_fillInStackTrace [this_3]
        ]
    ]

    ,
    procedure java_lang_Error_Error_0 [this_2]
    statements scope8 [
        assign field link3 next __gc_reflink_chain,
        assign field link3 nelm 1,
        assign field link3 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &this_2],
        assign field link3 serial 10003,
        assign field link3 magic 1917976149
        ,
        assign __gc_reflink_chain &link3
        ,
        procedurecall java_lang_Throwable_Throwable_0 [cast pointer record Throwable0 this_2]
    ]

    ,
    procedure java_lang_VirtualMachineError_VirtualMachineError_0 [this_1]
    statements scope7 [
        assign field link4 next __gc_reflink_chain,
        assign field link4 nelm 1,
        assign field link4 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &this_1],
        assign field link4 serial 10004,
        assign field link4 magic 1917976149
        ,
        assign __gc_reflink_chain &link4
        ,
        procedurecall java_lang_Error_Error_0 [cast pointer record Error0 this_1]
    ]

    ,
    procedure java_lang_OutOfMemoryError_OutOfMemoryError_0 [this_0]
    statements scope6 [
        assign field link5 next __gc_reflink_chain,
        assign field link5 nelm 1,
        assign field link5 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &this_0],
        assign field link5 serial 10005,
        assign field link5 magic 1917976149
        ,
        assign __gc_reflink_chain &link5
        ,
        procedurecall java_lang_VirtualMachineError_VirtualMachineError_0 [cast pointer record VirtualMachineError0 this_0]
    ]

    ,
    procedure spar_compiler_Builder_outOfMemory_0 []
    statements scope5 [
        assign field link6 next __gc_reflink_chain,
        assign field link6 nelm 1,
        assign field link6 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &breakout1_0],
        assign field link6 serial 10006,
        assign field link6 magic 1917976149
        ,
        assign __gc_reflink_chain &link6
        ,
        assign breakout1_0 functioncall __init_OutOfMemoryError0 [new record OutOfMemoryError0]
        ,
        procedurecall java_lang_OutOfMemoryError_OutOfMemoryError_0 [breakout1_0]
        ,
        throw breakout1_0
    ]

    ,
    procedure spar_compiler_Builder_nulExit_0 [] pragma [noGC]
    statements [
        procedurecall Java_spar_compiler_DefaultExceptionHandler_exit ["Null pointer dereferenced"]
    ]

    ,
    externalprocedure Java_spar_compiler_GC_resetActiveBlockMarks [] pragma [noGC]
    ,
    externalprocedure Java_spar_compiler_GC_clearRefStackOverflow []
    ,
    localvariable obj_1 scoped pointer record Object0
    ,
    externalfunction Java_spar_compiler_GC_firstReference [] pointer record Object0
    ,
    formalvariable obj_2 Java_spar_compiler_GC_pushRef pointer record Object0 final 
    ,
    externalprocedure Java_spar_compiler_GC_pushRef [obj_2]
    ,
    localvariable obj_3 scopee pointer record Object0
    ,
    externalfunction Java_spar_compiler_GC_popRef [] pointer record Object0
    ,
    formalvariable obj_4 Java_spar_compiler_GC_invokeMarkingMethod pointer record Object0 final 
    ,
    externalprocedure Java_spar_compiler_GC_invokeMarkingMethod [obj_4]
    ,
    procedure spar_compiler_GC_drainRefStack_0 [] pragma [no_GC_admin]
    statements scopee [
        assign obj_3 functioncall Java_spar_compiler_GC_popRef []
        ,
        while ( obj_3, <>, cast pointer record Object0 null )
            statements [
                procedurecall Java_spar_compiler_GC_invokeMarkingMethod [obj_3]
                ,
                assign obj_3 functioncall Java_spar_compiler_GC_popRef []
            ]
    ]

    ,
    externalfunction Java_spar_compiler_GC_nextReference [] pointer record Object0
    ,
    procedure spar_compiler_GC_markFromActiveRefs_0 [] pragma [no_GC_admin]
    statements scoped [
        assign obj_1 functioncall Java_spar_compiler_GC_firstReference []
        ,
        while ( obj_1, <>, cast pointer record Object0 null )
            statements [
                procedurecall Java_spar_compiler_GC_pushRef [obj_1]
                ,
                procedurecall spar_compiler_GC_drainRefStack_0 []
                ,
                assign obj_1 functioncall Java_spar_compiler_GC_nextReference []
            ]
    ]

    ,
    localvariable whilecond56_0 scopef boolean
    ,
    externalfunction Java_spar_compiler_GC_wasRefStackOverflow [] boolean
    ,
    localvariable obj_5 scope10 pointer record Object0
    ,
    externalfunction Java_spar_compiler_GC_firstBlock [] pointer record Object0
    ,
    formalvariable obj_6 Java_spar_compiler_GC_getMark pointer record Object0 final 
    ,
    externalfunction Java_spar_compiler_GC_getMark [obj_6] boolean
    ,
    externalfunction Java_spar_compiler_GC_nextBlock [] pointer record Object0
    ,
    procedure spar_compiler_GC_markFromBlockSet_0 [] pragma [no_GC_admin]
    statements scope10 [
        assign obj_5 functioncall Java_spar_compiler_GC_firstBlock []
        ,
        while ( obj_5, <>, cast pointer record Object0 null )
            statements [
                if functioncall Java_spar_compiler_GC_getMark [obj_5]
                    statements [
                        procedurecall Java_spar_compiler_GC_invokeMarkingMethod [obj_5]
                        ,
                        procedurecall spar_compiler_GC_drainRefStack_0 []
                    ]
                    statements [
                    ]
                ,
                assign obj_5 functioncall Java_spar_compiler_GC_nextBlock []
            ]
    ]

    ,
    localvariable obj_7 scope11 pointer record Object0
    ,
    localvariable delcount_0 scope12 int 0
    ,
    formalvariable obj_8 Java_spar_compiler_GC_invokeFinalize pointer record Object0 final 
    ,
    externalprocedure Java_spar_compiler_GC_invokeFinalize [obj_8]
    ,
    externalfunction Java_spar_compiler_GC_deleteBlock [] pointer record Object0
    ,
    function spar_compiler_GC_sweepUnmarkedBlocks_0 [] int pragma [no_GC_admin]
    statements scope11 [
        assign obj_7 functioncall Java_spar_compiler_GC_firstBlock []
        ,
        statements scope12 [
            while ( obj_7, <>, cast pointer record Object0 null )
                statements [
                    if (  not , functioncall Java_spar_compiler_GC_getMark [obj_7] )
                        statements [
                            procedurecall Java_spar_compiler_GC_invokeFinalize [obj_7]
                            ,
                            assign obj_7 functioncall Java_spar_compiler_GC_deleteBlock []
                            ,
                            assignop delcount_0 + 1
                        ]
                        statements [
                            assign obj_7 functioncall Java_spar_compiler_GC_nextBlock []
                        ]
                ]
            ,
            return delcount_0
        ]
    ]

    ,
    function spar_compiler_GC_collect_0 [] int pragma [no_GC_admin]
    statements [
        procedurecall Java_spar_compiler_GC_resetActiveBlockMarks []
        ,
        procedurecall Java_spar_compiler_GC_clearRefStackOverflow []
        ,
        procedurecall spar_compiler_GC_markFromActiveRefs_0 []
        ,
        statements scopef [
            assign whilecond56_0 functioncall Java_spar_compiler_GC_wasRefStackOverflow []
            ,
            while whilecond56_0
                statements [
                    procedurecall Java_spar_compiler_GC_clearRefStackOverflow []
                    ,
                    procedurecall spar_compiler_GC_markFromBlockSet_0 []
                    ,
                    assign whilecond56_0 functioncall Java_spar_compiler_GC_wasRefStackOverflow []
                ]
            ,
            statements scope13 [
                assign retvar0 functioncall spar_compiler_GC_sweepUnmarkedBlocks_0 []
                ,
                return retvar0
            ]
        ]
    ]

    ,
    localvariable retvar0 scope13 int
    ,
    localvariable link0 scope0 record __gc_reflink
    ,
    localvariable link2 scopec record __gc_reflink
    ,
    localvariable link1 scope9 record __gc_reflink
    ,
    localvariable link3 scope8 record __gc_reflink
    ,
    localvariable link4 scope7 record __gc_reflink
    ,
    localvariable link5 scope6 record __gc_reflink
    ,
    localvariable link6 scope5 record __gc_reflink
    ,
    record __introspection_type [nm:string, classno:int, last_subclassno:int,vtable:pointer record [],ivtable:pointer record [],flags:int,gcmarking:pointer procedure [pointer record Object0],finalizer:pointer procedure [pointer record Object0],ser_write:pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0],ser_read:pointer function [pointer record Object0,pointer record Object0] pointer record Object0]
    ,
    globalvariable t_introspection0 record __introspection_type record ["t", 3, 3, cast pointer record [] &t_vtable0, cast pointer record [] &ivtable0, 1,cast pointer procedure [pointer record Object0] &t_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Serializable_introspection0 record __introspection_type record ["java.io.Serializable", 0, 0, cast pointer record [] null, cast pointer record [] null, 1025,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Throwable_introspection0 record __introspection_type record ["java.lang.Throwable", 5, 9, cast pointer record [] &Throwable_vtable0, cast pointer record [] &ivtable2d, 1,cast pointer procedure [pointer record Object0] &Throwable_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write1,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read1]
    ,
    globalvariable String_introspection0 record __introspection_type record ["java.lang.String", 2, 2, cast pointer record [] &String_vtable0, cast pointer record [] &ivtable66, 17,cast pointer procedure [pointer record Object0] &String_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write0,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read0]
    ,
    globalvariable Object_introspection1 record __introspection_type record ["java.lang.Object", 1, 12, cast pointer record [] &Object_vtable0, cast pointer record [] &ivtable67, 1,cast pointer procedure [pointer record Object0] &Object_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable DefaultExceptionHandler_introspection0 record __introspection_type record ["spar.compiler.DefaultExceptionHandler", 4, 4, cast pointer record [] &DefaultExceptionHandler_vtable1, cast pointer record [] &ivtable68, 17,cast pointer procedure [pointer record Object0] &DefaultExceptionHandler_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Exception_introspection0 record __introspection_type record ["java.lang.Exception", 6, 6, cast pointer record [] &Exception_vtable0, cast pointer record [] &ivtable69, 1,cast pointer procedure [pointer record Object0] &Exception_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write2,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read2]
    ,
    globalvariable Introspection_introspection0 record __introspection_type record ["spar.compiler.Introspection", 10, 10, cast pointer record [] &Introspection_vtable0, cast pointer record [] &ivtable6a, 17,cast pointer procedure [pointer record Object0] &Introspection_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Builder_introspection0 record __introspection_type record ["spar.compiler.Builder", 11, 11, cast pointer record [] &Builder_vtable0, cast pointer record [] &ivtable6b, 17,cast pointer procedure [pointer record Object0] &Builder_mark1,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable OutOfMemoryError_introspection0 record __introspection_type record ["java.lang.OutOfMemoryError", 9, 9, cast pointer record [] &OutOfMemoryError_vtable0, cast pointer record [] &ivtable6c, 1,cast pointer procedure [pointer record Object0] &OutOfMemoryError_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write5,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read5]
    ,
    globalvariable VirtualMachineError_introspection0 record __introspection_type record ["java.lang.VirtualMachineError", 8, 9, cast pointer record [] &VirtualMachineError_vtable0, cast pointer record [] &ivtable6d, 1025,cast pointer procedure [pointer record Object0] &VirtualMachineError_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write4,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read4]
    ,
    globalvariable Error_introspection0 record __introspection_type record ["java.lang.Error", 7, 9, cast pointer record [] &Error_vtable0, cast pointer record [] &ivtable6e, 1,cast pointer procedure [pointer record Object0] &Error_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write3,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read3]
    ,
    globalvariable GC_introspection0 record __introspection_type record ["spar.compiler.GC", 12, 12, cast pointer record [] &GC_vtable0, cast pointer record [] &ivtable6f, 17,cast pointer procedure [pointer record Object0] &GC_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable __spar_rte_typelist array 13 pointer record __introspection_type array pointer record __introspection_type [
        &t_introspection0,
        &Serializable_introspection0,
        &Throwable_introspection0,
        &String_introspection0,
        &Object_introspection1,
        &DefaultExceptionHandler_introspection0,
        &Exception_introspection0,
        &Introspection_introspection0,
        &Builder_introspection0,
        &OutOfMemoryError_introspection0,
        &VirtualMachineError_introspection0,
        &Error_introspection0,
        &GC_introspection0
    ],
    globalvariable __spar_rte_typelist_length int 13
    ,
    // The representation of all interface types
    record __any_interface_type [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ]
    ,
    // The record type for the vtable of interface type java.io.Serializable
    record __t_Serializable_vtable0 [
    ]
    ,
    record __ivtable_type [
        java_io_Serializable: pointer record __t_Serializable_vtable0
    ]
    ,
    record t0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis0 markscope0 pointer record t0,
    procedure t_mark0 [markthis0] statements markscope0 [
    ],
    // The record type for the vtable of class type t
    record __t_t_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable t_vtable0 record __t_t_vtable0 record [
        &t_introspection0
    ]
    ,
    globalvariable ivtable0 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this0 scope14 pointer record t0,
    function __init_t0 [this0] pointer record t0 pragma [inline,nullvalue=false] statements scope14 [
        assign field *this0 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &t_vtable0,
        assign field *this0 __ivtable &ivtable0,
        return this0
    ]
    ,
    record Throwable0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthis1 markscope1 pointer record Throwable0,
    procedure Throwable_mark0 [markthis1] statements markscope1 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis1 java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis1 java_lang_Throwable_message_0],
    ],
    formalvariable writer1 ser_write_scope0 pointer record Object0,
    formalvariable handlebase0 ser_write_scope0 pointer record Object0,
    formalvariable data0 ser_write_scope0 pointer record Throwable0,
    procedure ser_write1 [writer1, handlebase0, data0] statements ser_write_scope0 [
        procedurecall ser_writeObject [writer1,handlebase0,cast pointer record Object0 field *data0 java_lang_Throwable_message_0],
    ],
    formalvariable reader0 scope15 pointer record Object0,
    formalvariable handlebase1 scope15 pointer record Object0,
    function ser_read1 [reader0, handlebase1]  pointer record Throwable0 statements scope15 [
        return cast pointer record Throwable0 null
    ],
    // The record type for the vtable of class type java.lang.Throwable
    record __t_Throwable_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Throwable_vtable0 record __t_Throwable_vtable0 record [
        &Throwable_introspection0
    ]
    ,
    globalvariable ivtab0 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable2d record __ivtable_type record [
        &ivtab0
    ],
    formalvariable this1 scope16 pointer record Throwable0,
    function __init_Throwable0 [this1] pointer record Throwable0 pragma [inline,nullvalue=false] statements scope16 [
        assign field *this1 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Throwable_vtable0,
        assign field *this1 __ivtable &ivtable2d,
        return this1
    ]
    ,
    record String0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_String_value_0: pointer shape [dontcare] char
        ,
        java_lang_String_offset_0: int
        ,
        java_lang_String_count_0: int
        ,
        java_lang_String_hash_0: int
        ,
        java_lang_String_interned_0: boolean
    ],
    formalvariable markthis2 markscope2 pointer record String0,
    procedure String_mark0 [markthis2] statements markscope2 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis2 java_lang_String_value_0],
    ],
    formalvariable writer2 ser_write_scope1 pointer record Object0,
    formalvariable handlebase2 ser_write_scope1 pointer record Object0,
    formalvariable data1 ser_write_scope1 pointer record String0,
    procedure ser_write0 [writer2, handlebase2, data1] statements ser_write_scope1 [
        procedurecall ser_writeArray [writer2,handlebase2,cast pointer record Object0 field *data1 java_lang_String_value_0],
        procedurecall ser_writeInt [writer2,handlebase2,field *data1 java_lang_String_offset_0],
        procedurecall ser_writeInt [writer2,handlebase2,field *data1 java_lang_String_count_0],
        procedurecall ser_writeInt [writer2,handlebase2,field *data1 java_lang_String_hash_0],
        procedurecall ser_writeBoolean [writer2,handlebase2,field *data1 java_lang_String_interned_0],
    ],
    formalvariable reader1 scope17 pointer record Object0,
    formalvariable handlebase3 scope17 pointer record Object0,
    function ser_read0 [reader1, handlebase3]  pointer record String0 statements scope17 [
        return cast pointer record String0 null
    ],
    // The record type for the vtable of class type java.lang.String
    record __t_String_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable String_vtable0 record __t_String_vtable0 record [
        &String_introspection0
    ]
    ,
    globalvariable ivtab1 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable66 record __ivtable_type record [
        &ivtab1
    ],
    formalvariable this2 scope18 pointer record String0,
    function __init_String0 [this2] pointer record String0 pragma [inline,nullvalue=false] statements scope18 [
        assign field *this2 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &String_vtable0,
        assign field *this2 __ivtable &ivtable66,
        return this2
    ]
    ,
    record Object0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis3 markscope3 pointer record Object0,
    procedure Object_mark0 [markthis3] statements markscope3 [
    ],
    // The record type for the vtable of class type java.lang.Object
    record __t_Object_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Object_vtable0 record __t_Object_vtable0 record [
        &Object_introspection1
    ]
    ,
    globalvariable ivtable67 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this3 scope19 pointer record Object0,
    function __init_Object0 [this3] pointer record Object0 pragma [inline,nullvalue=false] statements scope19 [
        assign field *this3 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Object_vtable0,
        assign field *this3 __ivtable &ivtable67,
        return this3
    ]
    ,
    record DefaultExceptionHandler0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis4 markscope4 pointer record DefaultExceptionHandler0,
    procedure DefaultExceptionHandler_mark0 [markthis4] statements markscope4 [
    ],
    // The record type for the vtable of class type spar.compiler.DefaultExceptionHandler
    record __t_DefaultExceptionHandler_vtable1 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable DefaultExceptionHandler_vtable1 record __t_DefaultExceptionHandler_vtable1 record [
        &DefaultExceptionHandler_introspection0
    ]
    ,
    globalvariable ivtable68 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this4 scope1a pointer record DefaultExceptionHandler0,
    function __init_DefaultExceptionHandler0 [this4] pointer record DefaultExceptionHandler0 pragma [inline,nullvalue=false] statements scope1a [
        assign field *this4 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &DefaultExceptionHandler_vtable1,
        assign field *this4 __ivtable &ivtable68,
        return this4
    ]
    ,
    record Exception0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthis5 markscope5 pointer record Exception0,
    procedure Exception_mark0 [markthis5] statements markscope5 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis5 java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis5 java_lang_Throwable_message_0],
    ],
    formalvariable writer3 ser_write_scope2 pointer record Object0,
    formalvariable handlebase4 ser_write_scope2 pointer record Object0,
    formalvariable data2 ser_write_scope2 pointer record Exception0,
    procedure ser_write2 [writer3, handlebase4, data2] statements ser_write_scope2 [
        procedurecall ser_writeObject [writer3,handlebase4,cast pointer record Object0 field *data2 java_lang_Throwable_message_0],
    ],
    formalvariable reader2 scope1b pointer record Object0,
    formalvariable handlebase5 scope1b pointer record Object0,
    function ser_read2 [reader2, handlebase5]  pointer record Exception0 statements scope1b [
        return cast pointer record Exception0 null
    ],
    // The record type for the vtable of class type java.lang.Exception
    record __t_Exception_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Exception_vtable0 record __t_Exception_vtable0 record [
        &Exception_introspection0
    ]
    ,
    globalvariable ivtab2 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable69 record __ivtable_type record [
        &ivtab2
    ],
    formalvariable this5 scope1c pointer record Exception0,
    function __init_Exception0 [this5] pointer record Exception0 pragma [inline,nullvalue=false] statements scope1c [
        assign field *this5 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Exception_vtable0,
        assign field *this5 __ivtable &ivtable69,
        return this5
    ]
    ,
    record Introspection0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis6 markscope6 pointer record Introspection0,
    procedure Introspection_mark0 [markthis6] statements markscope6 [
    ],
    // The record type for the vtable of class type spar.compiler.Introspection
    record __t_Introspection_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Introspection_vtable0 record __t_Introspection_vtable0 record [
        &Introspection_introspection0
    ]
    ,
    globalvariable ivtable6a record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this6 scope1d pointer record Introspection0,
    function __init_Introspection0 [this6] pointer record Introspection0 pragma [inline,nullvalue=false] statements scope1d [
        assign field *this6 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Introspection_vtable0,
        assign field *this6 __ivtable &ivtable6a,
        return this6
    ]
    ,
    record Builder1 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis7 markscope7 pointer record Builder1,
    procedure Builder_mark1 [markthis7] statements markscope7 [
    ],
    // The record type for the vtable of class type spar.compiler.Builder
    record __t_Builder_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Builder_vtable0 record __t_Builder_vtable0 record [
        &Builder_introspection0
    ]
    ,
    globalvariable ivtable6b record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this7 scope1e pointer record Builder1,
    function __init_Builder1 [this7] pointer record Builder1 pragma [inline,nullvalue=false] statements scope1e [
        assign field *this7 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Builder_vtable0,
        assign field *this7 __ivtable &ivtable6b,
        return this7
    ]
    ,
    record OutOfMemoryError0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthis8 markscope8 pointer record OutOfMemoryError0,
    procedure OutOfMemoryError_mark0 [markthis8] statements markscope8 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis8 java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis8 java_lang_Throwable_message_0],
    ],
    formalvariable writer4 ser_write_scope3 pointer record Object0,
    formalvariable handlebase6 ser_write_scope3 pointer record Object0,
    formalvariable data3 ser_write_scope3 pointer record OutOfMemoryError0,
    procedure ser_write5 [writer4, handlebase6, data3] statements ser_write_scope3 [
        procedurecall ser_writeObject [writer4,handlebase6,cast pointer record Object0 field *data3 java_lang_Throwable_message_0],
    ],
    formalvariable reader3 scope1f pointer record Object0,
    formalvariable handlebase7 scope1f pointer record Object0,
    function ser_read5 [reader3, handlebase7]  pointer record OutOfMemoryError0 statements scope1f [
        return cast pointer record OutOfMemoryError0 null
    ],
    // The record type for the vtable of class type java.lang.OutOfMemoryError
    record __t_OutOfMemoryError_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable OutOfMemoryError_vtable0 record __t_OutOfMemoryError_vtable0 record [
        &OutOfMemoryError_introspection0
    ]
    ,
    globalvariable ivtab3 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable6c record __ivtable_type record [
        &ivtab3
    ],
    formalvariable this8 scope20 pointer record OutOfMemoryError0,
    function __init_OutOfMemoryError0 [this8] pointer record OutOfMemoryError0 pragma [inline,nullvalue=false] statements scope20 [
        assign field *this8 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &OutOfMemoryError_vtable0,
        assign field *this8 __ivtable &ivtable6c,
        return this8
    ]
    ,
    record VirtualMachineError0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthis9 markscope9 pointer record VirtualMachineError0,
    procedure VirtualMachineError_mark0 [markthis9] statements markscope9 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis9 java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis9 java_lang_Throwable_message_0],
    ],
    formalvariable writer5 ser_write_scope4 pointer record Object0,
    formalvariable handlebase8 ser_write_scope4 pointer record Object0,
    formalvariable data4 ser_write_scope4 pointer record VirtualMachineError0,
    procedure ser_write4 [writer5, handlebase8, data4] statements ser_write_scope4 [
        procedurecall ser_writeObject [writer5,handlebase8,cast pointer record Object0 field *data4 java_lang_Throwable_message_0],
    ],
    formalvariable reader4 scope21 pointer record Object0,
    formalvariable handlebase9 scope21 pointer record Object0,
    function ser_read4 [reader4, handlebase9]  pointer record VirtualMachineError0 statements scope21 [
        return cast pointer record VirtualMachineError0 null
    ],
    // The record type for the vtable of class type java.lang.VirtualMachineError
    record __t_VirtualMachineError_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable VirtualMachineError_vtable0 record __t_VirtualMachineError_vtable0 record [
        &VirtualMachineError_introspection0
    ]
    ,
    globalvariable ivtab4 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable6d record __ivtable_type record [
        &ivtab4
    ],
    formalvariable this9 scope22 pointer record VirtualMachineError0,
    function __init_VirtualMachineError0 [this9] pointer record VirtualMachineError0 pragma [inline,nullvalue=false] statements scope22 [
        assign field *this9 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &VirtualMachineError_vtable0,
        assign field *this9 __ivtable &ivtable6d,
        return this9
    ]
    ,
    record Error0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthisa markscopea pointer record Error0,
    procedure Error_mark0 [markthisa] statements markscopea [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisa java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisa java_lang_Throwable_message_0],
    ],
    formalvariable writer6 ser_write_scope5 pointer record Object0,
    formalvariable handlebasea ser_write_scope5 pointer record Object0,
    formalvariable data5 ser_write_scope5 pointer record Error0,
    procedure ser_write3 [writer6, handlebasea, data5] statements ser_write_scope5 [
        procedurecall ser_writeObject [writer6,handlebasea,cast pointer record Object0 field *data5 java_lang_Throwable_message_0],
    ],
    formalvariable reader5 scope23 pointer record Object0,
    formalvariable handlebaseb scope23 pointer record Object0,
    function ser_read3 [reader5, handlebaseb]  pointer record Error0 statements scope23 [
        return cast pointer record Error0 null
    ],
    // The record type for the vtable of class type java.lang.Error
    record __t_Error_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Error_vtable0 record __t_Error_vtable0 record [
        &Error_introspection0
    ]
    ,
    globalvariable ivtab5 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable6e record __ivtable_type record [
        &ivtab5
    ],
    formalvariable thisa scope24 pointer record Error0,
    function __init_Error0 [thisa] pointer record Error0 pragma [inline,nullvalue=false] statements scope24 [
        assign field *thisa __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Error_vtable0,
        assign field *thisa __ivtable &ivtable6e,
        return thisa
    ]
    ,
    record GC0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthisb markscopeb pointer record GC0,
    procedure GC_mark0 [markthisb] statements markscopeb [
    ],
    // The record type for the vtable of class type spar.compiler.GC
    record __t_GC_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable GC_vtable0 record __t_GC_vtable0 record [
        &GC_introspection0
    ]
    ,
    globalvariable ivtable6f record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable thisb scope25 pointer record GC0,
    function __init_GC0 [thisb] pointer record GC0 pragma [inline,nullvalue=false] statements scope25 [
        assign field *thisb __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &GC_vtable0,
        assign field *thisb __ivtable &ivtable6f,
        return thisb
    ]
    ,
    formalvariable writer7 ser_writeBoolean pointer record Object0,
    formalvariable handlebasec ser_writeBoolean pointer record Object0,
    formalvariable data6 ser_writeBoolean Boolean,
    externalprocedure ser_writeBoolean[writer7,handlebasec,data6]
    ,
    formalvariable writer8 ser_writeChar pointer record Object0,
    formalvariable handlebased ser_writeChar pointer record Object0,
    formalvariable data7 ser_writeChar Char,
    externalprocedure ser_writeChar[writer8,handlebased,data7]
    ,
    formalvariable writer9 ser_writeByte pointer record Object0,
    formalvariable handlebasee ser_writeByte pointer record Object0,
    formalvariable data8 ser_writeByte Byte,
    externalprocedure ser_writeByte[writer9,handlebasee,data8]
    ,
    formalvariable writera ser_writeShort pointer record Object0,
    formalvariable handlebasef ser_writeShort pointer record Object0,
    formalvariable data9 ser_writeShort Short,
    externalprocedure ser_writeShort[writera,handlebasef,data9]
    ,
    formalvariable writerb ser_writeInt pointer record Object0,
    formalvariable handlebase10 ser_writeInt pointer record Object0,
    formalvariable dataa ser_writeInt Int,
    externalprocedure ser_writeInt[writerb,handlebase10,dataa]
    ,
    formalvariable writerc ser_writeLong pointer record Object0,
    formalvariable handlebase11 ser_writeLong pointer record Object0,
    formalvariable datab ser_writeLong Long,
    externalprocedure ser_writeLong[writerc,handlebase11,datab]
    ,
    formalvariable writerd ser_writeFloat pointer record Object0,
    formalvariable handlebase12 ser_writeFloat pointer record Object0,
    formalvariable datac ser_writeFloat Float,
    externalprocedure ser_writeFloat[writerd,handlebase12,datac]
    ,
    formalvariable writere ser_writeDouble pointer record Object0,
    formalvariable handlebase13 ser_writeDouble pointer record Object0,
    formalvariable datad ser_writeDouble Double,
    externalprocedure ser_writeDouble[writere,handlebase13,datad]
    ,
    formalvariable writerf ser_writeComplex pointer record Object0,
    formalvariable handlebase14 ser_writeComplex pointer record Object0,
    formalvariable datae ser_writeComplex Complex,
    externalprocedure ser_writeComplex[writerf,handlebase14,datae]
    ,
    formalvariable writer10 ser_writeString pointer record Object0,
    formalvariable handlebase15 ser_writeString pointer record Object0,
    formalvariable dataf ser_writeString String,
    externalprocedure ser_writeString[writer10,handlebase15,dataf]
    ,
    formalvariable writer11 ser_writeObject pointer record Object0,
    formalvariable handlebase16 ser_writeObject pointer record Object0,
    formalvariable data10 ser_writeObject pointer record Object0,
    externalprocedure ser_writeObject[writer11,handlebase16,data10]
    ,
    formalvariable writer12 ser_writeArray pointer record Object0,
    formalvariable handlebase17 ser_writeArray pointer record Object0,
    formalvariable data11 ser_writeArray pointer record Object0,
    externalprocedure ser_writeArray[writer12,handlebase17,data11]
    ,
    formalvariable reader6 ser_readBoolean pointer record Object0,
    formalvariable handlebase18 ser_readBoolean pointer record Object0,
    externalfunction ser_readBoolean[reader6,handlebase18] boolean
    ,
    formalvariable reader7 ser_readChar pointer record Object0,
    formalvariable handlebase19 ser_readChar pointer record Object0,
    externalfunction ser_readChar[reader7,handlebase19] char
    ,
    formalvariable reader8 ser_readByte pointer record Object0,
    formalvariable handlebase1a ser_readByte pointer record Object0,
    externalfunction ser_readByte[reader8,handlebase1a] byte
    ,
    formalvariable reader9 ser_readShort pointer record Object0,
    formalvariable handlebase1b ser_readShort pointer record Object0,
    externalfunction ser_readShort[reader9,handlebase1b] short
    ,
    formalvariable readera ser_readInt pointer record Object0,
    formalvariable handlebase1c ser_readInt pointer record Object0,
    externalfunction ser_readInt[readera,handlebase1c] int
    ,
    formalvariable readerb ser_readLong pointer record Object0,
    formalvariable handlebase1d ser_readLong pointer record Object0,
    externalfunction ser_readLong[readerb,handlebase1d] long
    ,
    formalvariable readerc ser_readFloat pointer record Object0,
    formalvariable handlebase1e ser_readFloat pointer record Object0,
    externalfunction ser_readFloat[readerc,handlebase1e] float
    ,
    formalvariable readerd ser_readDouble pointer record Object0,
    formalvariable handlebase1f ser_readDouble pointer record Object0,
    externalfunction ser_readDouble[readerd,handlebase1f] double
    ,
    formalvariable readere ser_readComplex pointer record Object0,
    formalvariable handlebase20 ser_readComplex pointer record Object0,
    externalfunction ser_readComplex[readere,handlebase20] complex
    ,
    formalvariable readerf ser_readString pointer record Object0,
    formalvariable handlebase21 ser_readString pointer record Object0,
    externalfunction ser_readString[readerf,handlebase21] string
    ,
    formalvariable reader10 ser_readObject pointer record Object0,
    formalvariable handlebase22 ser_readObject pointer record Object0,
    externalfunction ser_readObject[reader10,handlebase22] pointer record Object0
    ,
    formalvariable reader11 ser_readArray pointer record Object0,
    formalvariable handlebase23 ser_readArray pointer record Object0,
    externalfunction ser_readArray[reader11,handlebase23] pointer record Object0
    ,
    procedure VnusEventArrayBoundViolated [] statements [
        procedurecall spar_compiler_Builder_boundExit_1 []
    ]
    ,
    procedure VnusEventOutOfMemory [] statements [
        procedurecall spar_compiler_Builder_outOfMemory_0 []
    ]
    ,
    procedure VnusEventNullPointer [] statements [
        procedurecall spar_compiler_Builder_nulExit_0 []
    ]
    ,
    function VnusEventGarbageCollect [] int statements [
        return functioncall spar_compiler_GC_collect_0 []
    ]
]

statements [
    catch __main_x statements __main_catchblock [
        procedurecall t_main_0 []
    ]
    statements [
        procedurecall spar_compiler_DefaultExceptionHandler_handler_0 [cast pointer record Exception0 __main_x]
    ]
]
