JUNK = dist.lst

COMPILERSRCROOT = ../../../..
PRECIOUSJUNK =

MAKEFILE = Makefile

DISTFILES = $(MAKEFILE) $(wildcard *.spar)

all:

check:

tests:

clean:
	rm -f $(JUNK)

empty:
	rm -f $(JUNK) $(PRECIOUSJUNK)

include $(COMPILERSRCROOT)/Makefiles/Make.dist
