
// Generated by the Spar front-end

program

declarations [

    record genhello0 [
        __vtable: pointer record __t_vtable0
    ],
    formalvariable this0 scope4 pointer record genhello0,
    function __init_genhello0 [this0] pointer record genhello0 statements scope4 
	[ return this0 ]
]

statements [
]
