// Generated by the Spar front-end

program



declarations [
    function vnusbug_GiveNorm_0 [r_0] record [ field0:int ]
    statements scope0 [
        assign breakout0_0 getsize *notnullassert r_0 0
        ,
        return record [breakout0_0]
    ]
    ,
    formalvariable r_0 scope0 pointer shape [dontcare] double final 
    ,
    localvariable breakout0_0 scope0 int
]

statements [
    expression functioncall vnusbug_GiveNorm_0 [fillednew shape [23] double 0.0d null]
]
