/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;

/* ------ end of forward function declarations ------ */
// extern VnusInt vnusout;
// extern VnusBoolean a;
// extern VnusBoolean b;
// extern VnusBoolean c;
// extern VnusInt i;
// extern VnusInt j;
// extern VnusInt k;
/* ------ end of forward variable declarations ------ */

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    v__writeString( vnusout, "yes" );
    v__writeBoolean( vnusout, false );
    v__writeBoolean( vnusout, true );
    v__writeBoolean( vnusout, ((a&&b)&&c) );
    v__writeBoolean( vnusout, (a&&b) );
    v__writeBoolean( vnusout, ((a||b)||c) );
    v__writeBoolean( vnusout, (a||b) );
    v__writeBoolean( vnusout, ((a&&b)&&c) );
    v__writeBoolean( vnusout, (a&&b) );
    v__writeBoolean( vnusout, (a&&b) );
    v__writeBoolean( vnusout, ((a||b)||c) );
    v__writeBoolean( vnusout, (a||b) );
    v__writeBoolean( vnusout, (a||b) );
    v__writeInt( vnusout, ((i+j)+k) );
    v__writeInt( vnusout, j );
    v__writeInt( vnusout, (i+(-i)) );
    v__writeInt( vnusout, (i+(-2L)) );
    v__writeInt( vnusout, i );
    v__writeInt( vnusout, 0L );
    v__writeBoolean( vnusout, ((a&&b)&&c) );
    v__writeBoolean( vnusout, (a&&b) );
    v__writeBoolean( vnusout, ((a||b)||c) );
    v__writeBoolean( vnusout, (a||b) );
    v__writeInt( vnusout, ((i+j)+(-k)) );
    v__writeInt( vnusout, ((j+(-k))+i) );
    v__writeInt( vnusout, 128L );
    v__writeString( vnusout, "(i,+,0)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(0,+,i)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(i,-,0)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(i,or,0)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(0,or,i)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(i,*,1)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(1,*,i)" );
    v__writeInt( vnusout, i );
    v__writeString( vnusout, "(i,/,1)" );
    v__writeInt( vnusout, i );
    exit( 0 );
    return 0;
}
