// Generated by the Spar front-end

program

declarations [
    procedure spar_testsuite_main_0 []
    statements main0 [
        assign spar_testsuite_subpack_hello_staticfield_0 42
        ,
        procedurecall spar_testsuite_subpack_actor_say_0 []
    ]

    ,
    globalvariable spar_testsuite_subpack_hello_staticfield_0 int
    ,
    globalvariable spar_testsuite_subpack_hello_announcer_0 pointer record [  ] functioncall spar_testsuite_subpack_actor_actor_0 [new record [  ]]
    ,
    formalvariable this_0 scope0 pointer record [  ]
    ,
    formalvariable n_0 scope0 int
    ,
    function spar_testsuite_subpack_hello_hello_0 [this_0, n_0] pointer record [  ]
    statements scope0 [
        return this_0
    ]

    ,
    globalvariable spar_testsuite_subpack_hello_nofield_0 int
    ,
    procedure spar_testsuite_subpack_hello_nosay_0 []
    statements nosay0 [
        println [1, "Hello world from private method of subpackage??"]
    ]

    ,
    procedure spar_testsuite_subpack_hello_say_0 []
    statements say0 [
        println [1, "Hello world from subpackage"]
    ]

    ,
    procedure spar_testsuite_subpack_actor_say_0 []
    statements say1 [
        println [1, "To be or not to be"]
    ]

    ,
    formalvariable this_1 scope1 pointer record [  ]
    ,
    function spar_testsuite_subpack_actor_actor_0 [this_1] pointer record [  ]
    statements scope1 [
        return this_1
    ]

]

statements [
    procedurecall spar_testsuite_main_0 []
]
