/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;

void spar_testsuite_main_0( void );
VnusBase * spar_testsuite_subpack_hello_hello_0( VnusBase * this_0, VnusInt n_0 );
void spar_testsuite_subpack_hello_nosay_0( void );
void spar_testsuite_subpack_hello_say_0( void );
void spar_testsuite_subpack_actor_say_0( void );
VnusBase * spar_testsuite_subpack_actor_actor_0( VnusBase * this_1 );
/* ------ end of forward function declarations ------ */
extern VnusInt spar_testsuite_subpack_hello_staticfield_0;
extern VnusBase *spar_testsuite_subpack_hello_announcer_0;
extern VnusInt spar_testsuite_subpack_hello_nofield_0;
/* ------ end of forward variable declarations ------ */
VnusInt spar_testsuite_subpack_hello_staticfield_0;
VnusBase *spar_testsuite_subpack_hello_announcer_0;
VnusInt spar_testsuite_subpack_hello_nofield_0;

void spar_testsuite_main_0( void )
{
    spar_testsuite_subpack_hello_staticfield_0 = 42L;
    spar_testsuite_subpack_actor_say_0();
}

VnusBase * spar_testsuite_subpack_hello_hello_0( VnusBase * this_0, VnusInt n_0 )
{
    // Scope: scope0

    return this_0;
}

void spar_testsuite_subpack_hello_nosay_0( void )
{
    v__writeString( 1L, "Hello world from private method of subpackage??" );
    v__writeString( 1L, "\n" );
}

void spar_testsuite_subpack_hello_say_0( void )
{
    v__writeString( 1L, "Hello world from subpackage" );
    v__writeString( 1L, "\n" );
}

void spar_testsuite_subpack_actor_say_0( void )
{
    v__writeString( 1L, "To be or not to be" );
    v__writeString( 1L, "\n" );
}

VnusBase * spar_testsuite_subpack_actor_actor_0( VnusBase * this_1 )
{
    // Scope: scope1

    return this_1;
}

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    spar_testsuite_subpack_hello_announcer_0 = spar_testsuite_subpack_actor_actor_0( new VnusBase );
    spar_testsuite_main_0();
    exit( 0 );
    return 0;
}
