/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;
class record1;

class record1: public VnusBase {
public:
    inline record1()
     
    {}
    inline record1( VnusInt p_f0, VnusInt p_f1 ):
	field0(p_f0), field1(p_f1)
    {}
    VnusInt field0;
    VnusInt field1;
};

typedef VnusInt fn0(VnusBase);
typedef VnusInt fn1(record1);
/* ------ end of forward function declarations ------ */
extern VnusInt(*x)(VnusBase);
extern VnusInt(*y)(record1);
/* ------ end of forward variable declarations ------ */
VnusInt(*x)(VnusBase);
VnusInt(*y)(record1);

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    x = (fn0 *) y;
    exit( 0 );
    return 0;
}
