/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;
class record0;

class record0: public VnusBase {
public:
    inline record0()
     
    {}
    inline record0( VnusInt p_f0, VnusChar p_f1 ):
	field0(p_f0), field1(p_f1)
    {}
    VnusInt field0;
    VnusChar field1;
};

/* ------ end of forward function declarations ------ */
// extern VnusInt vnusout;
extern ShapeD1<VnusInt> a;
extern record0 b;
extern VnusInt i;
/* ------ end of forward variable declarations ------ */
ShapeD1<VnusInt> a( (VnusBase::markfntype) NULL, 10L );
record0 b = record0( 12L, 'x' );
VnusInt i = 3L;

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    exit( 0 );
    return 0;
}
