/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;

/* ------ end of forward function declarations ------ */
// extern VnusInt vnusout;
/* ------ end of forward variable declarations ------ */

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    {
	// Scope: outerscope
	VnusInt v;
	VnusInt array0[3] = { 1L, 2L, 3L };
	ShapeD1<VnusInt> x( (VnusBase::markfntype) NULL, array0, 3, 3L );

	{
	    // Scope: innerscope
	    VnusInt w;

	    w = 7L;
	    v = 8L;
	    v__writeString( vnusout, "v: " );
	    v__writeInt( vnusout, 8L );
	    v__writeString( vnusout, " w: " );
	    v__writeInt( vnusout, 7L );
	    v__writeString( vnusout, "\n" );
	}
	v = 9L;
	v__writeString( vnusout, "v: " );
	v__writeInt( vnusout, 9L );
	v__writeString( vnusout, "\n" );
    }
    exit( 0 );
    return 0;
}
