/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;

/* ------ end of forward function declarations ------ */
// extern VnusInt vnusout;
extern VnusDouble a;
extern VnusDouble b;
extern VnusDouble c;
/* ------ end of forward variable declarations ------ */
VnusDouble a = 2;
VnusDouble b = 0.5;
VnusDouble c = fmod(a,b);

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    exit( 0 );
    return 0;
}
