/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;
class record0;
class record1;
class record2;

class record0: public VnusBase {
public:
    inline record0()
     
    {}
    inline record0( VnusInt p_f0, VnusChar p_f1 ):
	field0(p_f0), field1(p_f1)
    {}
    VnusInt field0;
    VnusChar field1;
};

class record1: public VnusBase {
public:
    inline record1()
     
    {}
    inline record1( VnusInt p_f0, VnusChar p_f1, VnusInt p_f2 ):
	field0(p_f0), field1(p_f1), field2(p_f2)
    {}
    VnusInt field0;
    VnusChar field1;
    VnusInt field2;
};

class record2: public VnusBase {
public:
    inline record2()
     
    {}
    inline record2( VnusInt p_f0, record2 *p_f1 ):
	field0(p_f0), field1(p_f1)
    {}
    VnusInt field0;
    record2 *field1;
};

/* ------ end of forward function declarations ------ */
extern record0 a;
extern record1 b;
extern record0 c;
extern record1 d;
extern record0 *pa;
extern record1 *pb;
/* ------ end of forward variable declarations ------ */
record0 a = record0( 3L, 'a' );
record1 b = record1( 2L, 'b', (-1L) );
record0 c;
record1 d = record1( 0L, '@', 0L );
record0 *pa;
record1 *pb;

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    pa = new record0;
    pb = new record1;
    c = a;
    b = d;
    pa = (record0 *) pb;
    pb = (record1 *) pa;
    exit( 0 );
    return 0;
}
