/* This code was generated by the ParTool Vnus Backend. */

#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <vnuscomplex.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "vnusstio.h"
#include "vnusbaseclass.h"
#include "arrayalloc.h"
#include "vnusservice.h"
#include "shape.h"
#include "vnusrtl.h"
#include "arrayboundviolated.h"
#include "notnullassert.h"

VnusInt numberOfProcessors = 1;
int vnus_argc;
char **vnus_argv;

/* ------ end of forward function declarations ------ */
extern ShapeD1<VnusDouble> A;
/* ------ end of forward variable declarations ------ */
ShapeD1<VnusDouble> A( (VnusBase::markfntype) NULL, 30000L );

int main( int argc, char **argv )
{
    vnus_argc = argc;
    vnus_argv = argv;
    {
	for( VnusInt loop=0L; loop<500L; ++loop )
	{
	    {
		for( VnusInt i=0L; i<30000L; ++i )
		{
		    A[i] = ((VnusDouble) i*1.1);
		}
	    }
	}
    }
    v__writeString( 1L, "Checksum: " );
    v__writeDouble( 1L, A[1500L] );
    v__writeString( 1L, "\n" );
    exit( 0 );
    return 0;
}
