// File: argv.cc
//
// Access to vnus_argc and vnus_argv.

#include <stdio.h>
#include <vnusstd.h>
#include "spar-rtl.h"

// These should be generated by the Vnus backend.
extern int vnus_argc;
extern char **vnus_argv;

VnusInt Java_spar_compiler_Argv_getArgc()
{
    return (VnusInt) vnus_argc;
}

VnusString Java_spar_compiler_Argv_getArg( VnusInt i )
{
    if( i>=vnus_argc ){
	fprintf(
	    stderr,
	    "Cannot get argv element %d, there are only %d\n",
	    i,
	    vnus_argc-1
	);
	exit( 1 );
    }
    return (VnusString) vnus_argv[i];
}
