// Generated by the Spar front-end

program



declarations [
    record __gc_reflink [next:pointer record __gc_reflink,nelm:int,elm:array pointer pointer record Object0,serial:int,magic:int],
    globalvariable __gc_globallink record __gc_reflink,
    globalvariable __gc_reflink_chain pointer record __gc_reflink cast pointer record __gc_reflink null,
    formalvariable __main_x __main_catchblock pointer record []
    ,
    localvariable p1_0 scope0 pointer record Point0 cast pointer record Point0 null
    ,
    localvariable breakout1_0 scope0 pointer record Point0 cast pointer record Point0 null
    ,
    localvariable p2_0 scope5 pointer record Point0 cast pointer record Point0 null
    ,
    localvariable breakout2_0 scope5 pointer record ColoredPoint0 cast pointer record ColoredPoint0 null
    ,
    localvariable p3_0 scope9 pointer record Point0 cast pointer record Point0 null
    ,
    localvariable breakout3_0 scope9 pointer record ColoredPoint0 cast pointer record ColoredPoint0 null
    ,
    procedure genjlsexplicitcons_main_0 []
    statements scope0 [
        assign field link0 next __gc_reflink_chain,
        assign field link0 nelm 2,
        assign field link0 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &p1_0, cast pointer pointer record Object0 &breakout1_0],
        assign field link0 serial 10000,
        assign field link0 magic 1917976149
        ,
        assign __gc_reflink_chain &link0
        ,
        assign breakout1_0 functioncall __init_Point0 [new record Point0]
        ,
        statements scope26 [
            statements scope24 [
            ]
            ,
            statements scope25 [
                assign field *breakout1_0 Point_x_0 0
                ,
                assign field *breakout1_0 Point_y_0 0
            ]
            ,
            assign field *breakout1_0 Point_x_0 1
            ,
            assign field *breakout1_0 Point_y_0 2
        ]
        ,
        assign p1_0 breakout1_0
        ,
        statements scope5 [
            assign field link1 next &link0,
            assign field link1 nelm 2,
            assign field link1 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &p2_0, cast pointer pointer record Object0 &breakout2_0],
            assign field link1 serial 10001,
            assign field link1 magic 1917976149
            ,
            assign __gc_reflink_chain &link1
            ,
            assign breakout2_0 functioncall __init_ColoredPoint0 [new record ColoredPoint0]
            ,
            statements scope2c [
                statements scope2b [
                    statements scope29 [
                        statements scope27 [
                        ]
                        ,
                        statements scope28 [
                            assign field *cast pointer record Point0 breakout2_0 Point_x_0 0
                            ,
                            assign field *cast pointer record Point0 breakout2_0 Point_y_0 0
                        ]
                        ,
                        assign field *cast pointer record Point0 breakout2_0 Point_x_0 1
                        ,
                        assign field *cast pointer record Point0 breakout2_0 Point_y_0 2
                    ]
                    ,
                    statements scope2a [
                        assign field *breakout2_0 ColoredPoint_color_0 0
                    ]
                    ,
                    assign field *breakout2_0 ColoredPoint_color_0 0
                ]
            ]
            ,
            assign p2_0 cast pointer record Point0 breakout2_0
            ,
            statements scope9 [
                assign field link2 next &link1,
                assign field link2 nelm 2,
                assign field link2 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &p3_0, cast pointer pointer record Object0 &breakout3_0],
                assign field link2 serial 10002,
                assign field link2 magic 1917976149
                ,
                assign __gc_reflink_chain &link2
                ,
                assign breakout3_0 functioncall __init_ColoredPoint0 [new record ColoredPoint0]
                ,
                statements scope31 [
                    statements scope2f [
                        statements scope2d [
                        ]
                        ,
                        statements scope2e [
                            assign field *cast pointer record Point0 breakout3_0 Point_x_0 0
                            ,
                            assign field *cast pointer record Point0 breakout3_0 Point_y_0 0
                        ]
                        ,
                        assign field *cast pointer record Point0 breakout3_0 Point_x_0 1
                        ,
                        assign field *cast pointer record Point0 breakout3_0 Point_y_0 2
                    ]
                    ,
                    statements scope30 [
                        assign field *breakout3_0 ColoredPoint_color_0 0
                    ]
                    ,
                    assign field *breakout3_0 ColoredPoint_color_0 1
                ]
                ,
                assign p3_0 cast pointer record Point0 breakout3_0
            ]
        ]
    ]

    ,
    formalvariable x_3 scopea pointer record Exception0 final 
    ,
    localvariable id_1 scopea int
    ,
    formalvariable obj_0 Java_spar_compiler_Introspection_getClassId pointer record Object0 final 
    ,
    externalfunction Java_spar_compiler_Introspection_getClassId [obj_0] int pragma [noGC]
    ,
    localvariable s_0 scopeb string
    ,
    formalvariable id_2 Java_spar_compiler_Introspection_getClassName int final 
    ,
    externalfunction Java_spar_compiler_Introspection_getClassName [id_2] string pragma [noGC]
    ,
    formalvariable s_1 Java_spar_compiler_DefaultExceptionHandler_exit string final 
    ,
    externalprocedure Java_spar_compiler_DefaultExceptionHandler_exit [s_1] final  pragma [noGC]
    ,
    procedure spar_compiler_DefaultExceptionHandler_handler_0 [x_3] pragma [noGC]
    statements scopea [
        assign id_1 functioncall Java_spar_compiler_Introspection_getClassId [cast pointer record Object0 x_3]
        ,
        statements scopeb [
            assign s_0 functioncall Java_spar_compiler_Introspection_getClassName [id_1]
            ,
            procedurecall Java_spar_compiler_DefaultExceptionHandler_exit [s_0]
        ]
    ]

    ,
    procedure spar_compiler_Builder_boundExit_1 [] pragma [noGC]
    statements [
        procedurecall Java_spar_compiler_DefaultExceptionHandler_exit ["Array bound violated"]
    ]

    ,
    localvariable breakout4_0 scopec pointer record OutOfMemoryError0 cast pointer record OutOfMemoryError0 null
    ,
    formalvariable this_b Java_java_lang_Throwable_fillInStackTrace pointer record Throwable0 final 
    ,
    externalfunction Java_java_lang_Throwable_fillInStackTrace [this_b] pointer record Throwable0
    ,
    procedure spar_compiler_Builder_outOfMemory_0 []
    statements scopec [
        assign field link3 next __gc_reflink_chain,
        assign field link3 nelm 1,
        assign field link3 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &breakout4_0],
        assign field link3 serial 10003,
        assign field link3 magic 1917976149
        ,
        assign __gc_reflink_chain &link3
        ,
        assign breakout4_0 functioncall __init_OutOfMemoryError0 [new record OutOfMemoryError0]
        ,
        statements scope48 [
            statements scope47 [
                statements scope46 [
                    statements scope45 [
                        statements scope42 [
                        ]
                        ,
                        statements scope43 [
                            assign field *cast pointer record Throwable0 cast pointer record Error0 cast pointer record VirtualMachineError0 breakout4_0 java_lang_Throwable_backtrace_0 cast pointer record Object0 null
                            ,
                            assign field *cast pointer record Throwable0 cast pointer record Error0 cast pointer record VirtualMachineError0 breakout4_0 java_lang_Throwable_message_0 cast pointer record String0 null
                        ]
                        ,
                        assign field *cast pointer record Throwable0 cast pointer record Error0 cast pointer record VirtualMachineError0 breakout4_0 java_lang_Throwable_message_0 cast pointer record String0 null
                        ,
                        statements scope44 [
                            assign field link4 next &link3,
                            assign field link4 nelm 1,
                            assign field link4 elm cast array pointer pointer record Object0 array pointer pointer record Object0 [cast pointer pointer record Object0 &x_40010],
                            assign field link4 serial 10004,
                            assign field link4 magic 1917976149
                            ,
                            assign __gc_reflink_chain &link4
                            ,
                            assign x_40010 functioncall Java_java_lang_Throwable_fillInStackTrace [cast pointer record Throwable0 cast pointer record Error0 cast pointer record VirtualMachineError0 breakout4_0]
                        ]
                    ]
                ]
            ]
        ]
        ,
        throw breakout4_0
    ]

    ,
    procedure spar_compiler_Builder_nulExit_0 [] pragma [noGC]
    statements [
        procedurecall Java_spar_compiler_DefaultExceptionHandler_exit ["Null pointer dereferenced"]
    ]

    ,
    externalfunction Java_spar_compiler_GC_thereIsARootSet [] boolean
    ,
    externalprocedure Java_spar_compiler_GC_resetActiveBlockMarks [] pragma [noGC]
    ,
    externalprocedure Java_spar_compiler_GC_clearRefStackOverflow []
    ,
    externalfunction Java_spar_compiler_GC_firstReference [] pointer record Object0
    ,
    formalvariable obj_2 Java_spar_compiler_GC_pushRef pointer record Object0 final 
    ,
    externalprocedure Java_spar_compiler_GC_pushRef [obj_2]
    ,
    externalfunction Java_spar_compiler_GC_popRef [] pointer record Object0
    ,
    formalvariable obj_4 Java_spar_compiler_GC_invokeMarkingMethod pointer record Object0 final 
    ,
    externalprocedure Java_spar_compiler_GC_invokeMarkingMethod [obj_4]
    ,
    externalfunction Java_spar_compiler_GC_nextReference [] pointer record Object0
    ,
    localvariable whilecond56_0 scope16 boolean
    ,
    externalfunction Java_spar_compiler_GC_wasRefStackOverflow [] boolean
    ,
    externalfunction Java_spar_compiler_GC_firstBlock [] pointer record Object0
    ,
    formalvariable obj_6 Java_spar_compiler_GC_getMark pointer record Object0 final 
    ,
    externalfunction Java_spar_compiler_GC_getMark [obj_6] boolean
    ,
    externalfunction Java_spar_compiler_GC_nextBlock [] pointer record Object0
    ,
    externalfunction Java_spar_compiler_GC_firstUnmarkedBlock [] pointer record Object0
    ,
    formalvariable obj_8 Java_spar_compiler_GC_invokeFinalize pointer record Object0 final 
    ,
    externalprocedure Java_spar_compiler_GC_invokeFinalize [obj_8]
    ,
    externalfunction Java_spar_compiler_GC_deleteBlock [] pointer record Object0
    ,
    function spar_compiler_GC_collect_0 [] int pragma [no_GC_admin]
    statements [
        if (  not , functioncall Java_spar_compiler_GC_thereIsARootSet [] )
            statements [
                return 0
            ]
            statements [
            ]
        ,
        procedurecall Java_spar_compiler_GC_resetActiveBlockMarks []
        ,
        procedurecall Java_spar_compiler_GC_clearRefStackOverflow []
        ,
        statements scope4c [
            assign obj_10 functioncall Java_spar_compiler_GC_firstReference []
            ,
            while ( obj_10, <>, cast pointer record Object0 null )
                statements [
                    procedurecall Java_spar_compiler_GC_pushRef [obj_10]
                    ,
                    statements scope4b [
                        assign obj_311 functioncall Java_spar_compiler_GC_popRef []
                        ,
                        while ( obj_311, <>, cast pointer record Object0 null )
                            statements [
                                procedurecall Java_spar_compiler_GC_invokeMarkingMethod [obj_311]
                                ,
                                assign obj_311 functioncall Java_spar_compiler_GC_popRef []
                            ]
                    ]
                    ,
                    assign obj_10 functioncall Java_spar_compiler_GC_nextReference []
                ]
        ]
        ,
        statements scope16 [
            assign whilecond56_0 functioncall Java_spar_compiler_GC_wasRefStackOverflow []
            ,
            while whilecond56_0
                statements [
                    procedurecall Java_spar_compiler_GC_clearRefStackOverflow []
                    ,
                    statements scope4e [
                        assign obj_50 functioncall Java_spar_compiler_GC_firstBlock []
                        ,
                        while ( obj_50, <>, cast pointer record Object0 null )
                            statements [
                                if functioncall Java_spar_compiler_GC_getMark [obj_50]
                                    statements [
                                        procedurecall Java_spar_compiler_GC_invokeMarkingMethod [obj_50]
                                        ,
                                        statements scope4d [
                                            assign obj_320 functioncall Java_spar_compiler_GC_popRef []
                                            ,
                                            while ( obj_320, <>, cast pointer record Object0 null )
                                                statements [
                                                    procedurecall Java_spar_compiler_GC_invokeMarkingMethod [obj_320]
                                                    ,
                                                    assign obj_320 functioncall Java_spar_compiler_GC_popRef []
                                                ]
                                        ]
                                    ]
                                    statements [
                                    ]
                                ,
                                assign obj_50 functioncall Java_spar_compiler_GC_nextBlock []
                            ]
                    ]
                    ,
                    assign whilecond56_0 functioncall Java_spar_compiler_GC_wasRefStackOverflow []
                ]
            ,
            statements scope51 [
                statements scope50 [
                    assign obj_70 functioncall Java_spar_compiler_GC_firstUnmarkedBlock []
                    ,
                    statements scope4f [
                        while ( obj_70, <>, cast pointer record Object0 null )
                            statements [
                                procedurecall Java_spar_compiler_GC_invokeFinalize [obj_70]
                                ,
                                assign obj_70 functioncall Java_spar_compiler_GC_deleteBlock []
                                ,
                                assignop delcount_01 + 1
                            ]
                        ,
                        assign retvar0 delcount_01
                    ]
                ]
                ,
                return retvar0
            ]
        ]
    ]

    ,
    localvariable x_40010 scope44 pointer record Throwable0 cast pointer record Throwable0 null
    ,
    localvariable obj_10 scope4c pointer record Object0
    ,
    localvariable obj_311 scope4b pointer record Object0
    ,
    localvariable obj_50 scope4e pointer record Object0
    ,
    localvariable obj_320 scope4d pointer record Object0
    ,
    localvariable obj_70 scope50 pointer record Object0
    ,
    localvariable delcount_01 scope4f int 0
    ,
    localvariable retvar0 scope51 int
    ,
    localvariable link2 scope9 record __gc_reflink
    ,
    localvariable link1 scope5 record __gc_reflink
    ,
    localvariable link0 scope0 record __gc_reflink
    ,
    localvariable link4 scope44 record __gc_reflink
    ,
    localvariable link3 scopec record __gc_reflink
    ,
    record __introspection_type [nm:string, classno:int, last_subclassno:int,vtable:pointer record [],ivtable:pointer record [],flags:int,gcmarking:pointer procedure [pointer record Object0],finalizer:pointer procedure [pointer record Object0],ser_write:pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0],ser_read:pointer function [pointer record Object0,pointer record Object0] pointer record Object0]
    ,
    globalvariable Point_introspection0 record __introspection_type record ["Point", 4, 5, cast pointer record [] &Point_vtable0, cast pointer record [] &ivtable0, 0,cast pointer procedure [pointer record Object0] &Point_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable ColoredPoint_introspection0 record __introspection_type record ["ColoredPoint", 5, 5, cast pointer record [] &ColoredPoint_vtable0, cast pointer record [] &ivtable1, 0,cast pointer procedure [pointer record Object0] &ColoredPoint_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable genjlsexplicitcons_introspection0 record __introspection_type record ["genjlsexplicitcons", 3, 3, cast pointer record [] &genjlsexplicitcons_vtable0, cast pointer record [] &ivtable2, 1,cast pointer procedure [pointer record Object0] &genjlsexplicitcons_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Serializable_introspection0 record __introspection_type record ["java.io.Serializable", 0, 0, cast pointer record [] null, cast pointer record [] null, 1025,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Throwable_introspection0 record __introspection_type record ["java.lang.Throwable", 7, 11, cast pointer record [] &Throwable_vtable0, cast pointer record [] &ivtable2f, 1,cast pointer procedure [pointer record Object0] &Throwable_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write1,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read1]
    ,
    globalvariable String_introspection0 record __introspection_type record ["java.lang.String", 2, 2, cast pointer record [] &String_vtable0, cast pointer record [] &ivtable68, 17,cast pointer procedure [pointer record Object0] &String_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write0,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read0]
    ,
    globalvariable Object_introspection1 record __introspection_type record ["java.lang.Object", 1, 14, cast pointer record [] &Object_vtable0, cast pointer record [] &ivtable69, 1,cast pointer procedure [pointer record Object0] &Object_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable DefaultExceptionHandler_introspection0 record __introspection_type record ["spar.compiler.DefaultExceptionHandler", 6, 6, cast pointer record [] &DefaultExceptionHandler_vtable1, cast pointer record [] &ivtable6a, 17,cast pointer procedure [pointer record Object0] &DefaultExceptionHandler_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Exception_introspection0 record __introspection_type record ["java.lang.Exception", 8, 8, cast pointer record [] &Exception_vtable0, cast pointer record [] &ivtable6b, 1,cast pointer procedure [pointer record Object0] &Exception_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write2,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read2]
    ,
    globalvariable Introspection_introspection0 record __introspection_type record ["spar.compiler.Introspection", 12, 12, cast pointer record [] &Introspection_vtable0, cast pointer record [] &ivtable6c, 17,cast pointer procedure [pointer record Object0] &Introspection_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable Builder_introspection0 record __introspection_type record ["spar.compiler.Builder", 13, 13, cast pointer record [] &Builder_vtable0, cast pointer record [] &ivtable6d, 17,cast pointer procedure [pointer record Object0] &Builder_mark1,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable OutOfMemoryError_introspection0 record __introspection_type record ["java.lang.OutOfMemoryError", 11, 11, cast pointer record [] &OutOfMemoryError_vtable0, cast pointer record [] &ivtable6e, 1,cast pointer procedure [pointer record Object0] &OutOfMemoryError_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write5,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read5]
    ,
    globalvariable VirtualMachineError_introspection0 record __introspection_type record ["java.lang.VirtualMachineError", 10, 11, cast pointer record [] &VirtualMachineError_vtable0, cast pointer record [] &ivtable6f, 1025,cast pointer procedure [pointer record Object0] &VirtualMachineError_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write4,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read4]
    ,
    globalvariable Error_introspection0 record __introspection_type record ["java.lang.Error", 9, 11, cast pointer record [] &Error_vtable0, cast pointer record [] &ivtable70, 1,cast pointer procedure [pointer record Object0] &Error_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] &ser_write3,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 &ser_read3]
    ,
    globalvariable GC_introspection0 record __introspection_type record ["spar.compiler.GC", 14, 14, cast pointer record [] &GC_vtable0, cast pointer record [] &ivtable71, 17,cast pointer procedure [pointer record Object0] &GC_mark0,cast pointer procedure [pointer record Object0] null,cast pointer procedure [pointer record Object0,pointer record Object0,pointer record Object0] null,cast pointer function [pointer record Object0,pointer record Object0] pointer record Object0 null]
    ,
    globalvariable __spar_rte_typelist array 15 pointer record __introspection_type array pointer record __introspection_type [
        &Point_introspection0,
        &ColoredPoint_introspection0,
        &genjlsexplicitcons_introspection0,
        &Serializable_introspection0,
        &Throwable_introspection0,
        &String_introspection0,
        &Object_introspection1,
        &DefaultExceptionHandler_introspection0,
        &Exception_introspection0,
        &Introspection_introspection0,
        &Builder_introspection0,
        &OutOfMemoryError_introspection0,
        &VirtualMachineError_introspection0,
        &Error_introspection0,
        &GC_introspection0
    ],
    globalvariable __spar_rte_typelist_length int 15
    ,
    // The representation of all interface types
    record __any_interface_type [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ]
    ,
    // The record type for the vtable of interface type java.io.Serializable
    record __t_Serializable_vtable0 [
    ]
    ,
    record __ivtable_type [
        java_io_Serializable: pointer record __t_Serializable_vtable0
    ]
    ,
    record Point0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        Point_x_0: int
        ,
        Point_y_0: int
    ],
    formalvariable markthis0 markscope0 pointer record Point0,
    procedure Point_mark0 [markthis0] statements markscope0 [
    ],
    // The record type for the vtable of class type Point
    record __t_Point_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Point_vtable0 record __t_Point_vtable0 record [
        &Point_introspection0
    ]
    ,
    globalvariable ivtable0 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this0 scope52 pointer record Point0,
    function __init_Point0 [this0] pointer record Point0 pragma [inline,nullvalue=false] statements scope52 [
        assign field *this0 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Point_vtable0,
        assign field *this0 __ivtable &ivtable0,
        return this0
    ]
    ,
    record ColoredPoint0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        Point_x_0: int
        ,
        Point_y_0: int
        ,
        ColoredPoint_color_0: int
    ],
    formalvariable markthis1 markscope1 pointer record ColoredPoint0,
    procedure ColoredPoint_mark0 [markthis1] statements markscope1 [
    ],
    // The record type for the vtable of class type ColoredPoint
    record __t_ColoredPoint_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable ColoredPoint_vtable0 record __t_ColoredPoint_vtable0 record [
        &ColoredPoint_introspection0
    ]
    ,
    globalvariable ivtable1 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this1 scope53 pointer record ColoredPoint0,
    function __init_ColoredPoint0 [this1] pointer record ColoredPoint0 pragma [inline,nullvalue=false] statements scope53 [
        assign field *this1 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &ColoredPoint_vtable0,
        assign field *this1 __ivtable &ivtable1,
        return this1
    ]
    ,
    record genjlsexplicitcons0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis2 markscope2 pointer record genjlsexplicitcons0,
    procedure genjlsexplicitcons_mark0 [markthis2] statements markscope2 [
    ],
    // The record type for the vtable of class type genjlsexplicitcons
    record __t_genjlsexplicitcons_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable genjlsexplicitcons_vtable0 record __t_genjlsexplicitcons_vtable0 record [
        &genjlsexplicitcons_introspection0
    ]
    ,
    globalvariable ivtable2 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this2 scope54 pointer record genjlsexplicitcons0,
    function __init_genjlsexplicitcons0 [this2] pointer record genjlsexplicitcons0 pragma [inline,nullvalue=false] statements scope54 [
        assign field *this2 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &genjlsexplicitcons_vtable0,
        assign field *this2 __ivtable &ivtable2,
        return this2
    ]
    ,
    record Throwable0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthis3 markscope3 pointer record Throwable0,
    procedure Throwable_mark0 [markthis3] statements markscope3 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis3 java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis3 java_lang_Throwable_message_0],
    ],
    formalvariable writer1 ser_write_scope0 pointer record Object0,
    formalvariable handlebase0 ser_write_scope0 pointer record Object0,
    formalvariable data0 ser_write_scope0 pointer record Throwable0,
    procedure ser_write1 [writer1, handlebase0, data0] statements ser_write_scope0 [
        procedurecall ser_writeObject [writer1,handlebase0,cast pointer record Object0 field *data0 java_lang_Throwable_message_0],
    ],
    formalvariable reader0 scope55 pointer record Object0,
    formalvariable handlebase1 scope55 pointer record Object0,
    function ser_read1 [reader0, handlebase1]  pointer record Throwable0 statements scope55 [
        return cast pointer record Throwable0 null
    ],
    // The record type for the vtable of class type java.lang.Throwable
    record __t_Throwable_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Throwable_vtable0 record __t_Throwable_vtable0 record [
        &Throwable_introspection0
    ]
    ,
    globalvariable ivtab0 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable2f record __ivtable_type record [
        &ivtab0
    ],
    formalvariable this3 scope56 pointer record Throwable0,
    function __init_Throwable0 [this3] pointer record Throwable0 pragma [inline,nullvalue=false] statements scope56 [
        assign field *this3 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Throwable_vtable0,
        assign field *this3 __ivtable &ivtable2f,
        return this3
    ]
    ,
    record String0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_String_value_0: pointer shape [dontcare] char
        ,
        java_lang_String_offset_0: int
        ,
        java_lang_String_count_0: int
        ,
        java_lang_String_hash_0: int
        ,
        java_lang_String_interned_0: boolean
    ],
    formalvariable markthis4 markscope4 pointer record String0,
    procedure String_mark0 [markthis4] statements markscope4 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis4 java_lang_String_value_0],
    ],
    formalvariable writer2 ser_write_scope1 pointer record Object0,
    formalvariable handlebase2 ser_write_scope1 pointer record Object0,
    formalvariable data1 ser_write_scope1 pointer record String0,
    procedure ser_write0 [writer2, handlebase2, data1] statements ser_write_scope1 [
        procedurecall ser_writeArray [writer2,handlebase2,cast pointer record Object0 field *data1 java_lang_String_value_0],
        procedurecall ser_writeInt [writer2,handlebase2,field *data1 java_lang_String_offset_0],
        procedurecall ser_writeInt [writer2,handlebase2,field *data1 java_lang_String_count_0],
        procedurecall ser_writeInt [writer2,handlebase2,field *data1 java_lang_String_hash_0],
        procedurecall ser_writeBoolean [writer2,handlebase2,field *data1 java_lang_String_interned_0],
    ],
    formalvariable reader1 scope57 pointer record Object0,
    formalvariable handlebase3 scope57 pointer record Object0,
    function ser_read0 [reader1, handlebase3]  pointer record String0 statements scope57 [
        return cast pointer record String0 null
    ],
    // The record type for the vtable of class type java.lang.String
    record __t_String_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable String_vtable0 record __t_String_vtable0 record [
        &String_introspection0
    ]
    ,
    globalvariable ivtab1 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable68 record __ivtable_type record [
        &ivtab1
    ],
    formalvariable this4 scope58 pointer record String0,
    function __init_String0 [this4] pointer record String0 pragma [inline,nullvalue=false] statements scope58 [
        assign field *this4 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &String_vtable0,
        assign field *this4 __ivtable &ivtable68,
        return this4
    ]
    ,
    record Object0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis5 markscope5 pointer record Object0,
    procedure Object_mark0 [markthis5] statements markscope5 [
    ],
    // The record type for the vtable of class type java.lang.Object
    record __t_Object_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Object_vtable0 record __t_Object_vtable0 record [
        &Object_introspection1
    ]
    ,
    globalvariable ivtable69 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this5 scope59 pointer record Object0,
    function __init_Object0 [this5] pointer record Object0 pragma [inline,nullvalue=false] statements scope59 [
        assign field *this5 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Object_vtable0,
        assign field *this5 __ivtable &ivtable69,
        return this5
    ]
    ,
    record DefaultExceptionHandler0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis6 markscope6 pointer record DefaultExceptionHandler0,
    procedure DefaultExceptionHandler_mark0 [markthis6] statements markscope6 [
    ],
    // The record type for the vtable of class type spar.compiler.DefaultExceptionHandler
    record __t_DefaultExceptionHandler_vtable1 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable DefaultExceptionHandler_vtable1 record __t_DefaultExceptionHandler_vtable1 record [
        &DefaultExceptionHandler_introspection0
    ]
    ,
    globalvariable ivtable6a record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this6 scope5a pointer record DefaultExceptionHandler0,
    function __init_DefaultExceptionHandler0 [this6] pointer record DefaultExceptionHandler0 pragma [inline,nullvalue=false] statements scope5a [
        assign field *this6 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &DefaultExceptionHandler_vtable1,
        assign field *this6 __ivtable &ivtable6a,
        return this6
    ]
    ,
    record Exception0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthis7 markscope7 pointer record Exception0,
    procedure Exception_mark0 [markthis7] statements markscope7 [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis7 java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthis7 java_lang_Throwable_message_0],
    ],
    formalvariable writer3 ser_write_scope2 pointer record Object0,
    formalvariable handlebase4 ser_write_scope2 pointer record Object0,
    formalvariable data2 ser_write_scope2 pointer record Exception0,
    procedure ser_write2 [writer3, handlebase4, data2] statements ser_write_scope2 [
        procedurecall ser_writeObject [writer3,handlebase4,cast pointer record Object0 field *data2 java_lang_Throwable_message_0],
    ],
    formalvariable reader2 scope5b pointer record Object0,
    formalvariable handlebase5 scope5b pointer record Object0,
    function ser_read2 [reader2, handlebase5]  pointer record Exception0 statements scope5b [
        return cast pointer record Exception0 null
    ],
    // The record type for the vtable of class type java.lang.Exception
    record __t_Exception_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Exception_vtable0 record __t_Exception_vtable0 record [
        &Exception_introspection0
    ]
    ,
    globalvariable ivtab2 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable6b record __ivtable_type record [
        &ivtab2
    ],
    formalvariable this7 scope5c pointer record Exception0,
    function __init_Exception0 [this7] pointer record Exception0 pragma [inline,nullvalue=false] statements scope5c [
        assign field *this7 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Exception_vtable0,
        assign field *this7 __ivtable &ivtable6b,
        return this7
    ]
    ,
    record Introspection0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis8 markscope8 pointer record Introspection0,
    procedure Introspection_mark0 [markthis8] statements markscope8 [
    ],
    // The record type for the vtable of class type spar.compiler.Introspection
    record __t_Introspection_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Introspection_vtable0 record __t_Introspection_vtable0 record [
        &Introspection_introspection0
    ]
    ,
    globalvariable ivtable6c record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this8 scope5d pointer record Introspection0,
    function __init_Introspection0 [this8] pointer record Introspection0 pragma [inline,nullvalue=false] statements scope5d [
        assign field *this8 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Introspection_vtable0,
        assign field *this8 __ivtable &ivtable6c,
        return this8
    ]
    ,
    record Builder1 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthis9 markscope9 pointer record Builder1,
    procedure Builder_mark1 [markthis9] statements markscope9 [
    ],
    // The record type for the vtable of class type spar.compiler.Builder
    record __t_Builder_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Builder_vtable0 record __t_Builder_vtable0 record [
        &Builder_introspection0
    ]
    ,
    globalvariable ivtable6d record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this9 scope5e pointer record Builder1,
    function __init_Builder1 [this9] pointer record Builder1 pragma [inline,nullvalue=false] statements scope5e [
        assign field *this9 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Builder_vtable0,
        assign field *this9 __ivtable &ivtable6d,
        return this9
    ]
    ,
    record OutOfMemoryError0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthisa markscopea pointer record OutOfMemoryError0,
    procedure OutOfMemoryError_mark0 [markthisa] statements markscopea [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisa java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisa java_lang_Throwable_message_0],
    ],
    formalvariable writer4 ser_write_scope3 pointer record Object0,
    formalvariable handlebase6 ser_write_scope3 pointer record Object0,
    formalvariable data3 ser_write_scope3 pointer record OutOfMemoryError0,
    procedure ser_write5 [writer4, handlebase6, data3] statements ser_write_scope3 [
        procedurecall ser_writeObject [writer4,handlebase6,cast pointer record Object0 field *data3 java_lang_Throwable_message_0],
    ],
    formalvariable reader3 scope5f pointer record Object0,
    formalvariable handlebase7 scope5f pointer record Object0,
    function ser_read5 [reader3, handlebase7]  pointer record OutOfMemoryError0 statements scope5f [
        return cast pointer record OutOfMemoryError0 null
    ],
    // The record type for the vtable of class type java.lang.OutOfMemoryError
    record __t_OutOfMemoryError_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable OutOfMemoryError_vtable0 record __t_OutOfMemoryError_vtable0 record [
        &OutOfMemoryError_introspection0
    ]
    ,
    globalvariable ivtab3 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable6e record __ivtable_type record [
        &ivtab3
    ],
    formalvariable thisa scope60 pointer record OutOfMemoryError0,
    function __init_OutOfMemoryError0 [thisa] pointer record OutOfMemoryError0 pragma [inline,nullvalue=false] statements scope60 [
        assign field *thisa __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &OutOfMemoryError_vtable0,
        assign field *thisa __ivtable &ivtable6e,
        return thisa
    ]
    ,
    record VirtualMachineError0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthisb markscopeb pointer record VirtualMachineError0,
    procedure VirtualMachineError_mark0 [markthisb] statements markscopeb [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisb java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisb java_lang_Throwable_message_0],
    ],
    formalvariable writer5 ser_write_scope4 pointer record Object0,
    formalvariable handlebase8 ser_write_scope4 pointer record Object0,
    formalvariable data4 ser_write_scope4 pointer record VirtualMachineError0,
    procedure ser_write4 [writer5, handlebase8, data4] statements ser_write_scope4 [
        procedurecall ser_writeObject [writer5,handlebase8,cast pointer record Object0 field *data4 java_lang_Throwable_message_0],
    ],
    formalvariable reader4 scope61 pointer record Object0,
    formalvariable handlebase9 scope61 pointer record Object0,
    function ser_read4 [reader4, handlebase9]  pointer record VirtualMachineError0 statements scope61 [
        return cast pointer record VirtualMachineError0 null
    ],
    // The record type for the vtable of class type java.lang.VirtualMachineError
    record __t_VirtualMachineError_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable VirtualMachineError_vtable0 record __t_VirtualMachineError_vtable0 record [
        &VirtualMachineError_introspection0
    ]
    ,
    globalvariable ivtab4 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable6f record __ivtable_type record [
        &ivtab4
    ],
    formalvariable thisb scope62 pointer record VirtualMachineError0,
    function __init_VirtualMachineError0 [thisb] pointer record VirtualMachineError0 pragma [inline,nullvalue=false] statements scope62 [
        assign field *thisb __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &VirtualMachineError_vtable0,
        assign field *thisb __ivtable &ivtable6f,
        return thisb
    ]
    ,
    record Error0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
        ,
        java_lang_Throwable_backtrace_0: pointer record Object0
        ,
        java_lang_Throwable_message_0: pointer record String0
    ],
    formalvariable markthisc markscopec pointer record Error0,
    procedure Error_mark0 [markthisc] statements markscopec [
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisc java_lang_Throwable_backtrace_0],
        procedurecall Java_spar_compiler_GC_pushRef [cast pointer record Object0 field *markthisc java_lang_Throwable_message_0],
    ],
    formalvariable writer6 ser_write_scope5 pointer record Object0,
    formalvariable handlebasea ser_write_scope5 pointer record Object0,
    formalvariable data5 ser_write_scope5 pointer record Error0,
    procedure ser_write3 [writer6, handlebasea, data5] statements ser_write_scope5 [
        procedurecall ser_writeObject [writer6,handlebasea,cast pointer record Object0 field *data5 java_lang_Throwable_message_0],
    ],
    formalvariable reader5 scope63 pointer record Object0,
    formalvariable handlebaseb scope63 pointer record Object0,
    function ser_read3 [reader5, handlebaseb]  pointer record Error0 statements scope63 [
        return cast pointer record Error0 null
    ],
    // The record type for the vtable of class type java.lang.Error
    record __t_Error_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Error_vtable0 record __t_Error_vtable0 record [
        &Error_introspection0
    ]
    ,
    globalvariable ivtab5 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable70 record __ivtable_type record [
        &ivtab5
    ],
    formalvariable thisc scope64 pointer record Error0,
    function __init_Error0 [thisc] pointer record Error0 pragma [inline,nullvalue=false] statements scope64 [
        assign field *thisc __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Error_vtable0,
        assign field *thisc __ivtable &ivtable70,
        return thisc
    ]
    ,
    record GC0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        __dummy_outerthis: pointer record Object0
    ],
    formalvariable markthisd markscoped pointer record GC0,
    procedure GC_mark0 [markthisd] statements markscoped [
    ],
    // The record type for the vtable of class type spar.compiler.GC
    record __t_GC_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable GC_vtable0 record __t_GC_vtable0 record [
        &GC_introspection0
    ]
    ,
    globalvariable ivtable71 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable thisd scope65 pointer record GC0,
    function __init_GC0 [thisd] pointer record GC0 pragma [inline,nullvalue=false] statements scope65 [
        assign field *thisd __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &GC_vtable0,
        assign field *thisd __ivtable &ivtable71,
        return thisd
    ]
    ,
    formalvariable writer7 ser_writeBoolean pointer record Object0,
    formalvariable handlebasec ser_writeBoolean pointer record Object0,
    formalvariable data6 ser_writeBoolean Boolean,
    externalprocedure ser_writeBoolean[writer7,handlebasec,data6]
    ,
    formalvariable writer8 ser_writeChar pointer record Object0,
    formalvariable handlebased ser_writeChar pointer record Object0,
    formalvariable data7 ser_writeChar Char,
    externalprocedure ser_writeChar[writer8,handlebased,data7]
    ,
    formalvariable writer9 ser_writeByte pointer record Object0,
    formalvariable handlebasee ser_writeByte pointer record Object0,
    formalvariable data8 ser_writeByte Byte,
    externalprocedure ser_writeByte[writer9,handlebasee,data8]
    ,
    formalvariable writera ser_writeShort pointer record Object0,
    formalvariable handlebasef ser_writeShort pointer record Object0,
    formalvariable data9 ser_writeShort Short,
    externalprocedure ser_writeShort[writera,handlebasef,data9]
    ,
    formalvariable writerb ser_writeInt pointer record Object0,
    formalvariable handlebase10 ser_writeInt pointer record Object0,
    formalvariable dataa ser_writeInt Int,
    externalprocedure ser_writeInt[writerb,handlebase10,dataa]
    ,
    formalvariable writerc ser_writeLong pointer record Object0,
    formalvariable handlebase11 ser_writeLong pointer record Object0,
    formalvariable datab ser_writeLong Long,
    externalprocedure ser_writeLong[writerc,handlebase11,datab]
    ,
    formalvariable writerd ser_writeFloat pointer record Object0,
    formalvariable handlebase12 ser_writeFloat pointer record Object0,
    formalvariable datac ser_writeFloat Float,
    externalprocedure ser_writeFloat[writerd,handlebase12,datac]
    ,
    formalvariable writere ser_writeDouble pointer record Object0,
    formalvariable handlebase13 ser_writeDouble pointer record Object0,
    formalvariable datad ser_writeDouble Double,
    externalprocedure ser_writeDouble[writere,handlebase13,datad]
    ,
    formalvariable writerf ser_writeComplex pointer record Object0,
    formalvariable handlebase14 ser_writeComplex pointer record Object0,
    formalvariable datae ser_writeComplex Complex,
    externalprocedure ser_writeComplex[writerf,handlebase14,datae]
    ,
    formalvariable writer10 ser_writeString pointer record Object0,
    formalvariable handlebase15 ser_writeString pointer record Object0,
    formalvariable dataf ser_writeString String,
    externalprocedure ser_writeString[writer10,handlebase15,dataf]
    ,
    formalvariable writer11 ser_writeObject pointer record Object0,
    formalvariable handlebase16 ser_writeObject pointer record Object0,
    formalvariable data10 ser_writeObject pointer record Object0,
    externalprocedure ser_writeObject[writer11,handlebase16,data10]
    ,
    formalvariable writer12 ser_writeArray pointer record Object0,
    formalvariable handlebase17 ser_writeArray pointer record Object0,
    formalvariable data11 ser_writeArray pointer record Object0,
    externalprocedure ser_writeArray[writer12,handlebase17,data11]
    ,
    formalvariable reader6 ser_readBoolean pointer record Object0,
    formalvariable handlebase18 ser_readBoolean pointer record Object0,
    externalfunction ser_readBoolean[reader6,handlebase18] boolean
    ,
    formalvariable reader7 ser_readChar pointer record Object0,
    formalvariable handlebase19 ser_readChar pointer record Object0,
    externalfunction ser_readChar[reader7,handlebase19] char
    ,
    formalvariable reader8 ser_readByte pointer record Object0,
    formalvariable handlebase1a ser_readByte pointer record Object0,
    externalfunction ser_readByte[reader8,handlebase1a] byte
    ,
    formalvariable reader9 ser_readShort pointer record Object0,
    formalvariable handlebase1b ser_readShort pointer record Object0,
    externalfunction ser_readShort[reader9,handlebase1b] short
    ,
    formalvariable readera ser_readInt pointer record Object0,
    formalvariable handlebase1c ser_readInt pointer record Object0,
    externalfunction ser_readInt[readera,handlebase1c] int
    ,
    formalvariable readerb ser_readLong pointer record Object0,
    formalvariable handlebase1d ser_readLong pointer record Object0,
    externalfunction ser_readLong[readerb,handlebase1d] long
    ,
    formalvariable readerc ser_readFloat pointer record Object0,
    formalvariable handlebase1e ser_readFloat pointer record Object0,
    externalfunction ser_readFloat[readerc,handlebase1e] float
    ,
    formalvariable readerd ser_readDouble pointer record Object0,
    formalvariable handlebase1f ser_readDouble pointer record Object0,
    externalfunction ser_readDouble[readerd,handlebase1f] double
    ,
    formalvariable readere ser_readComplex pointer record Object0,
    formalvariable handlebase20 ser_readComplex pointer record Object0,
    externalfunction ser_readComplex[readere,handlebase20] complex
    ,
    formalvariable readerf ser_readString pointer record Object0,
    formalvariable handlebase21 ser_readString pointer record Object0,
    externalfunction ser_readString[readerf,handlebase21] string
    ,
    formalvariable reader10 ser_readObject pointer record Object0,
    formalvariable handlebase22 ser_readObject pointer record Object0,
    externalfunction ser_readObject[reader10,handlebase22] pointer record Object0
    ,
    formalvariable reader11 ser_readArray pointer record Object0,
    formalvariable handlebase23 ser_readArray pointer record Object0,
    externalfunction ser_readArray[reader11,handlebase23] pointer record Object0
    ,
    procedure VnusEventArrayBoundViolated [] statements [
        procedurecall spar_compiler_Builder_boundExit_1 []
    ]
    ,
    procedure VnusEventOutOfMemory [] statements [
        procedurecall spar_compiler_Builder_outOfMemory_0 []
    ]
    ,
    procedure VnusEventNullPointer [] statements [
        procedurecall spar_compiler_Builder_nulExit_0 []
    ]
    ,
    function VnusEventGarbageCollect [] int statements [
        return functioncall spar_compiler_GC_collect_0 []
    ]
]

statements [
    catch __main_x statements __main_catchblock [
        procedurecall genjlsexplicitcons_main_0 []
    ]
    statements [
        procedurecall spar_compiler_DefaultExceptionHandler_handler_0 [cast pointer record Exception0 __main_x]
    ]
]
