#!/bin/sh
#
# Run a test that is supposed to succeed and generate certain Vnus code.

TIMBERSRCROOT=../../..
SPARFLAGS=

# Places of executables
FRONT=$TIMBERSRCROOT/frontends/spar/sparfront
VERBOSE=0
FORCEV=0
FILE=
SPARPATH=$TIMBERSRCROOT/frontends:$SPARPATH
export SPARPATH

for f; do
    case "$f" in
	-v)
	    VERBOSE=1;;

	-f)
	    FORCEV=1;;

	-*)
	    echo "unknown option '$f'"; exit 2 ;;

	*)
	    FILE=$f ;;
    esac
done

if [ x$FILE = x ]; then
    echo "No file specified"
    exit 2
fi
BASENAME=`basename $FILE .spar`
BASENAME=`basename $BASENAME .java`
OUTFILE=$BASENAME.v
ERRFILE=$BASENAME.err
TESTOUTFILE=$BASENAME.tv
TESTERRFILE=$BASENAME.testerr
FLAGSFILE=$BASENAME.flags
PROFFILE=$BASENAME.gprof
if [ ! -e $ERRFILE ]; then
    echo "Creating default (=empty) error reference file '$ERRFILE'"
    touch $ERRFILE
fi
if [ ! -e $OUTFILE ]; then
    echo "Creating default (=empty) reference file '$OUTFILE'"
    touch $OUTFILE
fi
if [ -e $FLAGSFILE ]; then
    SPARFLAGS="$SPARFLAGS `cat $FLAGSFILE`"
fi
if [ $VERBOSE = 1 ]; then
    echo spar $SPARFLAGS $FILE
fi
FAIL=0
$FRONT $SPARFLAGS $FILE -o $TESTOUTFILE 2> $TESTERRFILE
COMPILESTATUS=$?
if [ $COMPILESTATUS != 0 ]; then
    echo "Compilation failed with status code $COMPILESTATUS"
    FAIL=1
fi
CMD="diff $TESTERRFILE $ERRFILE"
if [ $VERBOSE = 1 ]; then
    echo $CMD
fi
$CMD
STATUS=$?
if [ $STATUS != 0 ]; then
    echo "Spar compiler error messages differ from reference."
    echo "If you think the reference is wrong, update with:"
    echo "    cp $TESTERRFILE $ERRFILE"
    FAIL=1
fi
CMD="diff $TESTOUTFILE $OUTFILE"
if [ $VERBOSE = 1 ]; then
    echo $CMD
fi
$CMD
STATUS=$?
if [ $STATUS != 0 ]; then
    if [ $FAIL = 0 ]; then
	if [ $FORCEV = 1 ]; then
	    cp $TESTOUTFILE $OUTFILE
	    echo "File $OUTFILE has been updated"
	else
	    echo "Output differs from reference."
	    echo "If you think the reference is wrong, update with:"
	    echo "    cp $TESTOUTFILE $OUTFILE"
	    FAIL=1
	fi
    fi
fi
if [ $FAIL = 1 ]; then
    exit 1
fi
# Put aside any profile that has been created during this run
if [ -e gmon.out ]; then
    mv gmon.out $PROFFILE
fi
rm -f $TESTOUTFILE $TESTERRFILE
exit 0
