// Generated by the Spar front-end

program

pragma [vnusprog_p]

declarations [
    globalvariable tst_i_0 int 3 pragma [statdecl_p]
    ,
    procedure tst_main_0 [args_0] pragma [method_p]
    statements scope11 [
        pragma [primary_p]
        assign tst_i_0 5
        ,
        foreach [k_0=0:10]
            statements pragma [block_p] [
                pragma [stmt_p]
                assign (*(*a_1, [3]), [1]) ( expressionpragma [expr_p] 12, +, 5 )
            ]
    ]
    ,
    procedure tst_main0_0 []
    statements [
        procedurecall tst_main_0 [functioncall spar_compiler_Argv_buildArgv_0 []]
    ]

    ,
    globalvariable java_lang_Object_needstatic_init_Object0_0 boolean true
    ,
    externalfunction Java_spar_compiler_Argv_getArgc [] int const 
    ,
    externalfunction Java_spar_compiler_Argv_getArg [n_0] string const 
    ,
    function spar_compiler_Argv_buildArgv_0 [] pointer shape [dontcare] pointer record String0
    statements scope0 [
        if spar_compiler_Argv_needstatic_init_Argv0_0
            statements [
                assign spar_compiler_Argv_needstatic_init_Argv0_0 false
            ]
            statements [
            ]
        ,
        assign argc_0 functioncall Java_spar_compiler_Argv_getArgc []
        ,
        statements scope1 [
            for [i_0=1:argc_0]
                statements [
                    assign (*res_0, [( i_0, -, 1 )]) functioncall spar_compiler_Internalize_internalize_1 [functioncall Java_spar_compiler_Argv_getArg [i_0]]
                ]
            ,
            return res_0
        ]
    ]

    ,
    globalvariable spar_compiler_Argv_needstatic_init_Argv0_0 boolean true
    ,
    localvariable argc_0 scope0 int
    ,
    procedure spar_compiler_Service_arraycopy_0 [src_0, srcOffset_0, dst_0, dstOffset_0, count_1]
    statements scope10 [
        if spar_compiler_Service_needstatic_init_Service0_0
            statements [
                assign spar_compiler_Service_needstatic_init_Service0_0 false
            ]
            statements [
            ]
        ,
        for [i_2=0:count_1]
            statements [
                assign (*dst_0, [( dstOffset_0, +, i_2 )]) (*src_0, [( srcOffset_0, +, i_2 )])
            ]
    ]

    ,
    globalvariable spar_compiler_Service_needstatic_init_Service0_0 boolean true
    ,
    globalvariable spar_compiler_Internalize_stringpool_0 pointer shape [dontcare] pointer record String0 cast pointer shape [dontcare] pointer record String0 null
    ,
    function spar_compiler_Internalize_internalize_0 [arr_0] pointer record String0
    statements scope3 [
        if spar_compiler_Internalize_needstatic_init_Internalize0_0
            statements [
                assign spar_compiler_Internalize_needstatic_init_Internalize0_0 false
            ]
            statements [
            ]
        ,
        if ( spar_compiler_Internalize_stringpool_0, =, cast pointer shape [dontcare] pointer record String0 null )
            statements [
                assign spar_compiler_Internalize_stringpool_0 fillednew shape [0] pointer record String0 cast pointer record String0 null
            ]
            statements [
            ]
        ,
        for [i_1=0:getlength *spar_compiler_Internalize_stringpool_0]
            statements scope4 [
                if ( functioncall *field *cast pointer record __t_String_vtable0 field *e_0 __vtable __vte_java_lang_String_compareTo_1 [e_0, arr_0] , =, 0 )
                    statements [
                        return e_0
                    ]
                    statements [
                    ]
            ]
        ,
        statements scopea [
            assign pos_2 getlength *spar_compiler_Internalize_stringpool_0
            ,
            setsize *spar_compiler_Internalize_stringpool_0 [( pos_2, +, 1 )]
            ,
            statements scopeb [
                assign s_2 functioncall java_lang_String_String_9 [functioncall __init_String0 [new record String0], arr_0]
                ,
                assign (*spar_compiler_Internalize_stringpool_0, [pos_2]) s_2
                ,
                return s_2
            ]
        ]
    ]

    ,
    externalprocedure Java_spar_compiler_Internalize_unicodify [buf_1, s_1]
    ,
    function spar_compiler_Internalize_internalize_1 [s_0] pointer record String0
    statements scope2 [
        if spar_compiler_Internalize_needstatic_init_Internalize0_0
            statements [
                assign spar_compiler_Internalize_needstatic_init_Internalize0_0 false
            ]
            statements [
            ]
        ,
        procedurecall Java_spar_compiler_Internalize_unicodify [buf_0, s_0]
        ,
        return functioncall spar_compiler_Internalize_internalize_0 [buf_0]
    ]

    ,
    globalvariable spar_compiler_Internalize_needstatic_init_Internalize0_0 boolean true
    ,
    function java_lang_String_String_9 [this_1, other_0] pointer record String0
    statements scopec [
        if java_lang_String_needstatic_init_String0_0
            statements [
                assign java_lang_String_needstatic_init_String0_0 false
            ]
            statements [
            ]
        ,
        assign this_1 functioncall java_lang_String_dynamic_init_String0_0 [this_1]
        ,
        assign breakout19_1 getlength *other_0
        ,
        assign this_1 functioncall java_lang_String_String_a [this_1, breakout18_1, 0, breakout19_1]
        ,
        return this_1
    ]

    ,
    function java_lang_String_String_a [this_3, other_1, offset_0, count_0] pointer record String0
    statements scopee [
        if java_lang_String_needstatic_init_String0_0
            statements [
                assign java_lang_String_needstatic_init_String0_0 false
            ]
            statements [
            ]
        ,
        statements scopef [
            if java_lang_Object_needstatic_init_Object0_0
                statements [
                    assign java_lang_Object_needstatic_init_Object0_0 false
                ]
                statements [
                ]
            ,
            assign retvar0_0 this0
        ]
        ,
        assign this_3 cast pointer record String0 retvar0_0
        ,
        assign this_3 functioncall java_lang_String_dynamic_init_String0_0 [this_3]
        ,
        assign field *this_3 java_lang_String_value_0 fillednew shape [count_0] char '\0'
        ,
        assign field *this_3 java_lang_String_count_0 count_0
        ,
        if ( count_0, >, 0 )
            statements [
                procedurecall spar_compiler_Service_arraycopy_0 [other_1, offset_0, field *this_3 java_lang_String_value_0, 0, count_0]
            ]
            statements [
            ]
        ,
        return this_3
    ]

    ,
    function java_lang_String_compareTo_1 [this_0, s1_0] int
    statements scope5 [
        assign breakout23_0 getlength *s1_0
        ,
        assign minLen_0 functioncall java_lang_Math_min_2 [breakout22_0, breakout23_0]
        ,
        statements scope7 [
            while ( pos_1, <, minLen_0 )
                statements scope8 [
                    if ( cast int c_0, <>, cast int c1_0 )
                        statements [
                            return ( cast int c_0, -, cast int c1_0 )
                        ]
                        statements [
                        ]
                    ,
                    assign pos_1 ( pos_1, +, 1 )
                ]
        ]
        ,
        statements scope9 [
            assign breakout25_0 getlength *s1_0
            ,
            return ( breakout24_0, -, breakout25_0 )
        ]
    ]

    ,
    function java_lang_String_dynamic_init_String0_0 [this_2] pointer record String0
    statements scoped [
        assign field *this_2 java_lang_String_value_0 cast pointer shape [dontcare] char null
        ,
        assign field *this_2 java_lang_String_offset_0 0
        ,
        assign field *this_2 java_lang_String_count_0 0
        ,
        assign field *this_2 java_lang_String_hash_0 0
        ,
        assign field *this_2 java_lang_String_interned_0 false
        ,
        return this_2
    ]

    ,
    globalvariable java_lang_String_needstatic_init_String0_0 boolean true
    ,
    localvariable res_0 scope1 pointer shape [dontcare] pointer record String0 fillednew shape [( argc_0, -, 1 )] pointer record String0 cast pointer record String0 null
    ,
    cardinalityvariable i_0
    ,
    formalvariable n_0 Java_spar_compiler_Argv_getArg int
    ,
    formalvariable s_0 scope2 string
    ,
    localvariable buf_0 scope2 pointer shape [dontcare] char fillednew shape [20] char '\0'
    ,
    formalvariable buf_1 Java_spar_compiler_Internalize_unicodify pointer shape [dontcare] char
    ,
    formalvariable s_1 Java_spar_compiler_Internalize_unicodify string
    ,
    formalvariable arr_0 scope3 pointer shape [dontcare] char
    ,
    cardinalityvariable i_1
    ,
    localvariable e_0 scope4 pointer record String0 (*spar_compiler_Internalize_stringpool_0, [i_1])
    ,
    formalvariable this_0 scope5 pointer record String0
    ,
    formalvariable s1_0 scope5 pointer shape [dontcare] char
    ,
    localvariable minLen_0 scope5 int
    ,
    localvariable breakout22_0 scope5 int field *this_0 java_lang_String_count_0 const 
    ,
    localvariable breakout23_0 scope5 int const 
    ,
    function java_lang_Math_min_2 [a_0, b_0] int
    statements scope6 [
        if java_lang_Math_needstatic_init_Math0_0
            statements [
                assign java_lang_Math_needstatic_init_Math0_0 false
            ]
            statements [
            ]
        ,
        return if ( a_0, <, b_0 ) a_0 b_0
    ]

    ,
    globalvariable java_lang_Math_needstatic_init_Math0_0 boolean true
    ,
    formalvariable a_0 scope6 int
    ,
    formalvariable b_0 scope6 int
    ,
    localvariable pos_1 scope7 int 0
    ,
    localvariable c_0 scope8 char (*field *this_0 java_lang_String_value_0, [( field *this_0 java_lang_String_offset_0, +, pos_1 )])
    ,
    localvariable c1_0 scope8 char (*s1_0, [pos_1])
    ,
    localvariable breakout24_0 scope9 int field *this_0 java_lang_String_count_0 const 
    ,
    localvariable breakout25_0 scope9 int const 
    ,
    localvariable pos_2 scopea int
    ,
    localvariable s_2 scopeb pointer record String0
    ,
    formalvariable this_1 scopec pointer record String0
    ,
    formalvariable other_0 scopec pointer shape [dontcare] char
    ,
    formalvariable this_2 scoped pointer record String0
    ,
    localvariable breakout18_1 scopec pointer shape [dontcare] char other_0 const 
    ,
    localvariable breakout19_1 scopec int const 
    ,
    formalvariable this_3 scopee pointer record String0
    ,
    formalvariable other_1 scopee pointer shape [dontcare] char
    ,
    formalvariable offset_0 scopee int
    ,
    formalvariable count_0 scopee int
    ,
    localvariable retvar0_0 scopee pointer record Object0
    ,
    localvariable this0 scopef pointer record Object0 cast pointer record Object0 this_3
    ,
    formalvariable src_0 scope10 pointer shape [dontcare] char
    ,
    formalvariable srcOffset_0 scope10 int
    ,
    formalvariable dst_0 scope10 pointer shape [dontcare] char
    ,
    formalvariable dstOffset_0 scope10 int
    ,
    formalvariable count_1 scope10 int
    ,
    cardinalityvariable i_2
    ,
    formalvariable args_0 scope11 pointer shape [dontcare] pointer record String0 pragma [param_p]
    ,
    localvariable a_1 scope11 pointer shape [dontcare] pragma [decldim_p] pointer shape [dontcare] pragma [primtype_p] int expressionpragma [new_p] fillednew pragma [vector_p] shape [100] pragma [newdim_p] pointer shape [dontcare] int cast pointer shape [dontcare] int null pragma [locvar_p]
    ,
    cardinalityvariable k_0
    ,
    record __introspection_type [nm:string, classno:int, last_subclassno:int,vtable:pointer record [],ivtable:pointer record [],flags:int]
    ,
    globalvariable tst_introspection0 record __introspection_type record ["tst", 2, 2, cast pointer record [] &tst_vtable0, cast pointer record [] &ivtable0, 1]
    ,
    globalvariable Object_introspection0 record __introspection_type record ["java.lang.Object", 1, 8, cast pointer record [] &Object_vtable0, cast pointer record [] &ivtable1, 1]
    ,
    globalvariable Argv_introspection0 record __introspection_type record ["spar.compiler.Argv", 3, 3, cast pointer record [] &Argv_vtable0, cast pointer record [] &ivtable2, 17]
    ,
    globalvariable Serializable_introspection0 record __introspection_type record ["java.io.Serializable", 0, 0, cast pointer record [] null, cast pointer record [] null, 1025]
    ,
    globalvariable Service_introspection0 record __introspection_type record ["spar.compiler.Service", 8, 8, cast pointer record [] &Service_vtable0, cast pointer record [] &ivtable7, 17]
    ,
    globalvariable Internalize_introspection0 record __introspection_type record ["spar.compiler.Internalize", 5, 5, cast pointer record [] &Internalize_vtable0, cast pointer record [] &ivtable1d, 17]
    ,
    globalvariable String_introspection0 record __introspection_type record ["java.lang.String", 4, 4, cast pointer record [] &String_vtable0, cast pointer record [] &ivtable1e, 17]
    ,
    globalvariable Random_introspection0 record __introspection_type record ["java.util.Random", 7, 7, cast pointer record [] &Random_vtable0, cast pointer record [] &ivtable1f, 1]
    ,
    globalvariable Math_introspection0 record __introspection_type record ["java.lang.Math", 6, 6, cast pointer record [] &Math_vtable0, cast pointer record [] &ivtable20, 17]
    ,
    globalvariable __spar_rte_typelist shape [9] pointer record __introspection_type shape [9] pointer record __introspection_type [
        &tst_introspection0,
        &Object_introspection0,
        &Argv_introspection0,
        &Serializable_introspection0,
        &Service_introspection0,
        &Internalize_introspection0,
        &String_introspection0,
        &Random_introspection0,
        &Math_introspection0
    ]
    ,
    // The representation of all interface types
    record __any_interface_type [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ]
    ,
    // The record type for the vtable of interface type java.io.Serializable
    record __t_Serializable_vtable0 [
    ]
    ,
    record __ivtable_type [
        java_io_Serializable: pointer record __t_Serializable_vtable0
    ]
    ,
    record tst0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        tst_j_0: int
    ],
    // The record type for the vtable of class type tst
    record __t_tst_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable tst_vtable0 record __t_tst_vtable0 record [
        &tst_introspection0
    ]
    ,
    globalvariable ivtable0 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this1 scope12 pointer record tst0,
    function __init_tst0 [this1] pointer record tst0 statements scope12 [ assign field *this1 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &tst_vtable0, assign field *this1 __ivtable &ivtable0, return this1 ]
    ,
    record Object0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type java.lang.Object
    record __t_Object_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Object_vtable0 record __t_Object_vtable0 record [
        &Object_introspection0
    ]
    ,
    globalvariable ivtable1 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this2 scope13 pointer record Object0,
    function __init_Object0 [this2] pointer record Object0 statements scope13 [ assign field *this2 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Object_vtable0, assign field *this2 __ivtable &ivtable1, return this2 ]
    ,
    record Argv0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type spar.compiler.Argv
    record __t_Argv_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Argv_vtable0 record __t_Argv_vtable0 record [
        &Argv_introspection0
    ]
    ,
    globalvariable ivtable2 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this3 scope14 pointer record Argv0,
    function __init_Argv0 [this3] pointer record Argv0 statements scope14 [ assign field *this3 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Argv_vtable0, assign field *this3 __ivtable &ivtable2, return this3 ]
    ,
    record Service0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type spar.compiler.Service
    record __t_Service_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Service_vtable0 record __t_Service_vtable0 record [
        &Service_introspection0
    ]
    ,
    globalvariable ivtable7 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this4 scope15 pointer record Service0,
    function __init_Service0 [this4] pointer record Service0 statements scope15 [ assign field *this4 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Service_vtable0, assign field *this4 __ivtable &ivtable7, return this4 ]
    ,
    record Internalize0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type spar.compiler.Internalize
    record __t_Internalize_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Internalize_vtable0 record __t_Internalize_vtable0 record [
        &Internalize_introspection0
    ]
    ,
    globalvariable ivtable1d record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this5 scope16 pointer record Internalize0,
    function __init_Internalize0 [this5] pointer record Internalize0 statements scope16 [ assign field *this5 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Internalize_vtable0, assign field *this5 __ivtable &ivtable1d, return this5 ]
    ,
    record String0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        java_lang_String_value_0: pointer shape [dontcare] char
        ,
        java_lang_String_offset_0: int
        ,
        java_lang_String_count_0: int
        ,
        java_lang_String_hash_0: int
        ,
        java_lang_String_interned_0: boolean
    ],
    // The record type for the vtable of class type java.lang.String
    record __t_String_vtable0 [
        __introspection: pointer record __introspection_type,
        __vte_java_lang_String_compareTo_1: pointer function [pointer record String0, pointer shape [dontcare] char] int
    ],
    globalvariable String_vtable0 record __t_String_vtable0 record [
        &String_introspection0
        ,
        cast pointer function [pointer record String0, pointer shape [dontcare] char] int &java_lang_String_compareTo_1
    ]
    ,
    globalvariable ivtab0 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable1e record __ivtable_type record [
        &ivtab0
    ],
    formalvariable this6 scope17 pointer record String0,
    function __init_String0 [this6] pointer record String0 statements scope17 [ assign field *this6 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &String_vtable0, assign field *this6 __ivtable &ivtable1e, return this6 ]
    ,
    record Random0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
        ,
        java_util_Random_seed_0: long
        ,
        java_util_Random_haveNextNextGaussian_0: boolean
        ,
        java_util_Random_nextNextGaussian_0: double
        ,
        java_util_Random_p1_0: long
        ,
        java_util_Random_p2_0: long
        ,
        java_util_Random_mask_0: long
    ],
    // The record type for the vtable of class type java.util.Random
    record __t_Random_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Random_vtable0 record __t_Random_vtable0 record [
        &Random_introspection0
    ]
    ,
    globalvariable ivtab1 record __t_Serializable_vtable0 record [
    ]
    ,
    globalvariable ivtable1f record __ivtable_type record [
        &ivtab1
    ],
    formalvariable this7 scope18 pointer record Random0,
    function __init_Random0 [this7] pointer record Random0 statements scope18 [ assign field *this7 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Random_vtable0, assign field *this7 __ivtable &ivtable1f, return this7 ]
    ,
    record Math0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type java.lang.Math
    record __t_Math_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Math_vtable0 record __t_Math_vtable0 record [
        &Math_introspection0
    ]
    ,
    globalvariable ivtable20 record __ivtable_type record [
        cast pointer record __t_Serializable_vtable0 null
    ],
    formalvariable this8 scope19 pointer record Math0,
    function __init_Math0 [this8] pointer record Math0 statements scope19 [ assign field *this8 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Math_vtable0, assign field *this8 __ivtable &ivtable20, return this8 ]
]

statements [
    procedurecall tst_main0_0 []
]
