// Generated by the Spar front-end

program

declarations [
    procedure tst2_main_0 []
    statements scope0 [
        pragma [on=(at dsp2D (cyclic 7) _)]
        assign a_0 7
        ,
        pragma [on=(at dsp2D _all (cyclic 3 17))]
        assign a_0 8
        ,
        pragma [on=(at dsp2D _all @a_0)]
        assign a_0 0
        ,
        pragma [on=_all,on=_]
        assign a_0 2
    ]
    ,
    localvariable a_0 scope0 int
]

statements [
    procedurecall tst2_main_0 []
]
