// Generated by the Spar front-end

program

declarations [
    procedure tst3_main_0 []
    statements scope0 [
        assign a_0 ( expressionpragma [on=(at dsp2D (cyclic 7) _)] 7, *, expressionpragma [on=(at dsp2D _all (cyclic 3 17))] 8 )
    ],
    localvariable a_0 scope0 int
]

statements [
    procedurecall tst3_main_0 []
]
