// Generated by the Spar front-end

program



declarations [
    procedure tst5_main_0 []
    statements scope0 [
        foreach [i_0=0:10]
            statements [
                assign (*a_0, [i_0]) ( (*a_0, [i_0]), +, ( (*a_0, [( i_0, +, 1 )]), *, (*a_0, [( i_0, +, 2 )]) ) )
            ]
    ],
    localvariable a_0 scope0 pragma [on=(lambda (i) (at dsp2D i))] pointer shape [dontcare] int,
    cardinalityvariable i_0
]

statements [
    procedurecall tst5_main_0 []
]
