// Generated by the Spar front-end

program

declarations [
    function tst6_fun_0 [a_1, b_0] int
    statements scope2 [
        if tst6_needstatic_init_tst60_0
            statements [
                assign tst6_needstatic_init_tst60_0 false
            ]
            statements [
            ]
    ]

    ,
    procedure tst6_main_0 []
    statements scope0 [
        if tst6_needstatic_init_tst60_0
            statements [
                assign tst6_needstatic_init_tst60_0 false
            ]
            statements [
            ]
        ,
        foreach [i_0=0:10]
            statements scope1 [
                assign breakout1_0 functioncall tst6_fun_0 [(*a_0, [( i_0, +, 1 )]), (*a_0, [( i_0, +, 2 )])]
                ,
                assign (*a_0, [i_0]) ( breakout0_0, +, breakout1_0 )
            ]
    ]

    ,
    globalvariable tst6_needstatic_init_tst60_0 boolean true
    ,
    localvariable a_0 scope0 pragma [on=(lambda (i) (at dsp2D i))] pointer shape [dontcare] int
    ,
    cardinalityvariable i_0
    ,
    localvariable breakout0_0 scope1 int (*a_0, [i_0]) const 
    ,
    formalvariable a_1 scope2 int
    ,
    formalvariable b_0 scope2 int
    ,
    localvariable breakout1_0 scope1 int const 
    ,
    record __introspection_type [nm:string, classno:int, last_subclassno:int,vtable:pointer record [],ivtable:pointer record [],flags:int]
    ,
    globalvariable tst6_introspection0 record __introspection_type record ["tst6", 2, 2, cast pointer record [] &tst6_vtable0, cast pointer record [] &ivtable0, 1]
    ,
    globalvariable Object_introspection0 record __introspection_type record ["java.lang.Object", 1, 2, cast pointer record [] &Object_vtable0, cast pointer record [] &ivtable1, 1]
    ,
    globalvariable __spar_rte_typelist shape [2] pointer record __introspection_type shape [2] pointer record __introspection_type [
        &tst6_introspection0,
        &Object_introspection0
    ]
    ,
    // The representation of all interface types
    record __any_interface_type [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ]
    ,
    record __ivtable_type [
    ]
    ,
    record tst60 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type tst6
    record __t_tst6_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable tst6_vtable0 record __t_tst6_vtable0 record [
        &tst6_introspection0
    ]
    ,
    globalvariable ivtable0 record __ivtable_type record [
    ],
    formalvariable this0 scope3 pointer record tst60,
    function __init_tst60 [this0] pointer record tst60 statements scope3 [ assign field *this0 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &tst6_vtable0, assign field *this0 __ivtable &ivtable0, return this0 ]
    ,
    record Object0 [
        __vtable: pointer record [ __introspection: pointer record __introspection_type ],
        __ivtable: pointer record __ivtable_type
    ],
    // The record type for the vtable of class type java.lang.Object
    record __t_Object_vtable0 [
        __introspection: pointer record __introspection_type
    ],
    globalvariable Object_vtable0 record __t_Object_vtable0 record [
        &Object_introspection0
    ]
    ,
    globalvariable ivtable1 record __ivtable_type record [
    ],
    formalvariable this1 scope4 pointer record Object0,
    function __init_Object0 [this1] pointer record Object0 statements scope4 [ assign field *this1 __vtable cast pointer record [ __introspection: pointer record __introspection_type ] &Object_vtable0, assign field *this1 __ivtable &ivtable1, return this1 ]
]

statements [
    procedurecall tst6_main_0 []
]
