// Generated by the Spar front-end

program

declarations [
    globalvariable tst7_c_0 int 0
    ,
    procedure tst7_max_0 [a_1, b_0, d_0]
    statements scope1 [
        assign tst7_c_0 if ( a_1, >, b_0 ) a_1 ( b_0, +, d_0 )
    ]

    ,
    procedure tst7_main_0 []
    statements scope0 [
        procedurecall tst7_max_0 [(*a_0, [( i_0, +, 1 )]), (*a_0, [i_0]), (*a_0, [i_0])]
    ]

    ,
    globalvariable tst7_needstatic_init_tst70_0 boolean true
    ,
    localvariable a_0 scope0 pragma [on=(lambda (i) (at dsp2D i))] pointer shape [dontcare] int
    ,
    localvariable i_0 scope0 int 2
    ,
    formalvariable a_1 scope1 int
    ,
    formalvariable b_0 scope1 int
    ,
    formalvariable d_0 scope1 int
]

statements [
    procedurecall tst7_main_0 []
]
